// AUTO-GENERATED by scripts/resolve-franchise-data.mjs — do not edit by hand.
// Card data (title, poster, year) for every entry of every curated franchise,
// keyed by `${source}:${kind}:${sourceId}`. Pre-resolved so getWatchOrder and
// the /watch-order index render curated sagas with zero TMDB/Jikan calls at
// request time. Regenerate when curated-franchises.ts changes.

export type CuratedEntryData = { title: string; posterUrl: string | null; year: number | null };

export const FRANCHISE_ENTRY_DATA: Record<string, CuratedEntryData> = {
  "tmdb:movie:1771": {
    title: "Capitán América: El primer vengador",
    posterUrl: "https://image.tmdb.org/t/p/w342/i5eSA5DK5iAv53SB4yv57bN56o6.jpg",
    year: 2011,
  },
  "tmdb:movie:299537": {
    title: "Capitana Marvel",
    posterUrl: "https://image.tmdb.org/t/p/w342/5SPa7dZ85p54xa7E9tHRmfKq5ce.jpg",
    year: 2019,
  },
  "tmdb:movie:1726": {
    title: "Iron Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/tFCTNx7foAsUQpgu2x1KjAJD1wT.jpg",
    year: 2008,
  },
  "tmdb:movie:10138": {
    title: "Iron Man 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/ayyJVOV5I4MGjti7nIHC3mVCagR.jpg",
    year: 2010,
  },
  "tmdb:movie:1724": {
    title: "El increíble Hulk",
    posterUrl: "https://image.tmdb.org/t/p/w342/rCTSJzsU2GkH5uLwP1RFb3OjtLs.jpg",
    year: 2008,
  },
  "tmdb:movie:10195": {
    title: "Thor",
    posterUrl: "https://image.tmdb.org/t/p/w342/qFAVW4XJaxhj7PcpiUI5hhO9bOX.jpg",
    year: 2011,
  },
  "tmdb:movie:24428": {
    title: "Los Vengadores",
    posterUrl: "https://image.tmdb.org/t/p/w342/ugX4WZJO3jEvTOerctAWJLinujo.jpg",
    year: 2012,
  },
  "tmdb:movie:68721": {
    title: "Iron Man 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/cW0fOIZONkgeiMJDYzqUcgl4MUn.jpg",
    year: 2013,
  },
  "tmdb:movie:76338": {
    title: "Thor: el mundo oscuro",
    posterUrl: "https://image.tmdb.org/t/p/w342/cs5YLwGBCJBold74avD3NecO5Zc.jpg",
    year: 2013,
  },
  "tmdb:movie:100402": {
    title: "Capitán América: El soldado de invierno",
    posterUrl: "https://image.tmdb.org/t/p/w342/3Zv12uAqBxj4xAdeHeVySEQzY1o.jpg",
    year: 2014,
  },
  "tmdb:movie:118340": {
    title: "Guardianes de la galaxia",
    posterUrl: "https://image.tmdb.org/t/p/w342/zqZNnuMtrmK99Xux91KiCdnZxgb.jpg",
    year: 2014,
  },
  "tmdb:movie:283995": {
    title: "Guardianes de la Galaxia Vol. 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/kdg6Y06jfq9FV7qknWNcKLYtBJn.jpg",
    year: 2017,
  },
  "tmdb:movie:99861": {
    title: "Vengadores: La era de Ultrón",
    posterUrl: "https://image.tmdb.org/t/p/w342/3Lz6h5rlCFNNyCZRaRJ2ZjtBnAE.jpg",
    year: 2015,
  },
  "tmdb:movie:102899": {
    title: "Ant-Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/zwuE28gSXlLFLgueqMe9b7xKy1f.jpg",
    year: 2015,
  },
  "tmdb:movie:271110": {
    title: "Capitán América: Civil War",
    posterUrl: "https://image.tmdb.org/t/p/w342/jPPy7tCfglppQo6J9nGwU6UmJ8X.jpg",
    year: 2016,
  },
  "tmdb:movie:497698": {
    title: "Viuda Negra",
    posterUrl: "https://image.tmdb.org/t/p/w342/uR3ex7LZrX3lbIMNb87WBXzCWM.jpg",
    year: 2021,
  },
  "tmdb:movie:315635": {
    title: "Spider-Man: Homecoming",
    posterUrl: "https://image.tmdb.org/t/p/w342/yJfPC6pjSJ5VOsVyXhx5PXBe0mR.jpg",
    year: 2017,
  },
  "tmdb:movie:284052": {
    title: "Doctor Strange",
    posterUrl: "https://image.tmdb.org/t/p/w342/wJEZI3PWyMW7qcW6n9jyCh7Cclf.jpg",
    year: 2016,
  },
  "tmdb:movie:284054": {
    title: "Black Panther",
    posterUrl: "https://image.tmdb.org/t/p/w342/lAPzezdc5E6DFnttJwCWXZ9A9C6.jpg",
    year: 2018,
  },
  "tmdb:movie:284053": {
    title: "Thor: Ragnarok",
    posterUrl: "https://image.tmdb.org/t/p/w342/pGtkLdk4rnF2A3Yz2BHiTgRwMU4.jpg",
    year: 2017,
  },
  "tmdb:movie:363088": {
    title: "Ant-Man y la Avispa",
    posterUrl: "https://image.tmdb.org/t/p/w342/bvYI6i9lQ3bsup9PgnMF3YYr8ZR.jpg",
    year: 2018,
  },
  "tmdb:movie:299536": {
    title: "Vengadores: Infinity War",
    posterUrl: "https://image.tmdb.org/t/p/w342/ksBQ4oHQDdJwND8H90ay8CbMihU.jpg",
    year: 2018,
  },
  "tmdb:movie:299534": {
    title: "Vengadores: Endgame",
    posterUrl: "https://image.tmdb.org/t/p/w342/br6krBFpaYmCSglLBWRuhui7tPc.jpg",
    year: 2019,
  },
  "tmdb:movie:429617": {
    title: "Spider-Man: Lejos de casa",
    posterUrl: "https://image.tmdb.org/t/p/w342/o59zDVJDIehGcWZsMUGU5SN0V0D.jpg",
    year: 2019,
  },
  "tmdb:movie:1893": {
    title: "La guerra de las galaxias. Episodio I: La amenaza fantasma",
    posterUrl: "https://image.tmdb.org/t/p/w342/4rjatbWmGGmu0DZs6WNpXaUWqWN.jpg",
    year: 1999,
  },
  "tmdb:movie:1894": {
    title: "La guerra de las galaxias. Episodio II: El ataque de los clones",
    posterUrl: "https://image.tmdb.org/t/p/w342/pwwBIUqVSWrCBuUAvbaNdf7VajF.jpg",
    year: 2002,
  },
  "tmdb:movie:1895": {
    title: "La guerra de las galaxias. Episodio III: La venganza de los Sith",
    posterUrl: "https://image.tmdb.org/t/p/w342/5dj0ERxM8NxoiWBdlY6TT9PJmKi.jpg",
    year: 2005,
  },
  "tmdb:movie:11": {
    title: "La guerra de las galaxias",
    posterUrl: "https://image.tmdb.org/t/p/w342/ahT4ObS7XKedQkOSpGr1wQ97aKA.jpg",
    year: 1977,
  },
  "tmdb:movie:1891": {
    title: "El imperio contraataca",
    posterUrl: "https://image.tmdb.org/t/p/w342/eU7KcNAOeZj9PBIcGUMSsuJz8qj.jpg",
    year: 1980,
  },
  "tmdb:movie:1892": {
    title: "El retorno del Jedi",
    posterUrl: "https://image.tmdb.org/t/p/w342/rKMmXzdm7eRgmlwYo7iq3klT7wJ.jpg",
    year: 1983,
  },
  "tmdb:movie:140607": {
    title: "Star Wars: El despertar de la fuerza",
    posterUrl: "https://image.tmdb.org/t/p/w342/vI86GLIkT5pP3ZfNs2EvmTrBLBm.jpg",
    year: 2015,
  },
  "tmdb:movie:181808": {
    title: "Star Wars: Los últimos Jedi",
    posterUrl: "https://image.tmdb.org/t/p/w342/7SNzh1fY3YJ8Y8MX93pZF5cJHaH.jpg",
    year: 2017,
  },
  "tmdb:movie:181812": {
    title: "Star Wars: El ascenso de Skywalker",
    posterUrl: "https://image.tmdb.org/t/p/w342/oeQxq6If4DcW6ADIYCF9SQwKov.jpg",
    year: 2019,
  },
  "anilist:anime:10087": {
    title: "Fate/Zero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1887/117644l.webp",
    year: 2011,
  },
  "anilist:anime:11741": {
    title: "Fate/Zero Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1522/117645l.webp",
    year: 2012,
  },
  "anilist:anime:22297": {
    title: "Fate/stay night [Unlimited Blade Works]",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/67333l.webp",
    year: 2014,
  },
  "anilist:anime:28701": {
    title: "Fate/stay night [Unlimited Blade Works] Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1881/124810l.webp",
    year: 2015,
  },
  "anilist:anime:25537": {
    title: "Fate/stay night: Heaven's Feel - I. Presage Flower",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1274/102213l.webp",
    year: 2017,
  },
  "anilist:anime:33049": {
    title: "Fate/stay night: Heaven's Feel - II. Lost Butterfly",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1974/98158l.webp",
    year: 2019,
  },
  "anilist:anime:33050": {
    title: "Fate/stay night: Heaven's Feel - III. Spring Song",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1142/112957l.webp",
    year: 2020,
  },
  "anilist:anime:5081": {
    title: "Bakemonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/75274l.webp",
    year: 2009,
  },
  "anilist:anime:9260": {
    title: "Kizumonogatari Part 1: Iron-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1783/112810l.webp",
    year: 2016,
  },
  "anilist:anime:31757": {
    title: "Kizumonogatari Part 2: Hot-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1981/112812l.webp",
    year: 2016,
  },
  "anilist:anime:31758": {
    title: "Kizumonogatari Part 3: Cold-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1084/112813l.webp",
    year: 2017,
  },
  "anilist:anime:11597": {
    title: "Nisemonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1044/103654l.webp",
    year: 2012,
  },
  "anilist:anime:15689": {
    title: "Nekomonogatari Black",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1170/121597l.webp",
    year: 2012,
  },
  "anilist:anime:17074": {
    title: "Monogatari Series: Second Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1807/121534l.webp",
    year: 2013,
  },
  "anilist:anime:21855": {
    title: "Hanamonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/65755l.webp",
    year: 2014,
  },
  "anilist:anime:28025": {
    title: "Tsukimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/68259l.webp",
    year: 2014,
  },
  "anilist:anime:31181": {
    title: "Owarimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/76479l.webp",
    year: 2015,
  },
  "anilist:anime:32268": {
    title: "Koyomimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/77744l.webp",
    year: 2016,
  },
  "anilist:anime:35247": {
    title: "Owarimonogatari Second Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/87322l.webp",
    year: 2017,
  },
  "anilist:anime:36999": {
    title: "Zoku Owarimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1022/96168l.webp",
    year: 2019,
  },
  "anilist:anime:57864": {
    title: "Monogatari Series: Off & Monster Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1142/146776l.webp",
    year: 2024,
  },
  "anilist:anime:30": {
    title: "Neon Genesis Evangelion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1314/108941l.webp",
    year: 1995,
  },
  "anilist:anime:32": {
    title: "Neon Genesis Evangelion: The End of Evangelion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1404/98182l.webp",
    year: 1997,
  },
  "anilist:anime:2759": {
    title: "Evangelion: 1.0 You Are (Not) Alone",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/74975l.webp",
    year: 2007,
  },
  "anilist:anime:3784": {
    title: "Evangelion: 2.0 You Can (Not) Advance",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/74983l.webp",
    year: 2009,
  },
  "anilist:anime:3785": {
    title: "Evangelion: 3.0 You Can (Not) Redo",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/43201l.webp",
    year: 2012,
  },
  "anilist:anime:3786": {
    title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1422/113533l.webp",
    year: 2021,
  },
  "anilist:anime:9756": {
    title: "Puella Magi Madoka Magica",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/55225l.webp",
    year: 2011,
  },
  "anilist:anime:11977": {
    title: "Puella Magi Madoka Magica the Movie Part 1: Beginnings",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/42331l.webp",
    year: 2012,
  },
  "anilist:anime:11979": {
    title: "Puella Magi Madoka Magica the Movie Part 2: Eternal",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/42265l.webp",
    year: 2012,
  },
  "anilist:anime:11981": {
    title: "Puella Magi Madoka Magica the Movie: Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/54231l.webp",
    year: 2013,
  },
  "anilist:anime:1575": {
    title: "Code Geass: Lelouch of the Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1032/135088l.webp",
    year: 2006,
  },
  "anilist:anime:2904": {
    title: "Code Geass: Lelouch of the Rebellion R2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1088/135089l.webp",
    year: 2008,
  },
  "anilist:anime:34437": {
    title: "Code Geass: Lelouch of the Re;surrection",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1274/113436l.webp",
    year: 2019,
  },
  "anilist:anime:849": {
    title: "The Melancholy of Haruhi Suzumiya",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1470/137929l.webp",
    year: 2006,
  },
  "anilist:anime:4382": {
    title: "The Melancholy of Haruhi Suzumiya (2009)",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/75377l.webp",
    year: 2009,
  },
  "anilist:anime:7311": {
    title: "The Disappearance of Haruhi Suzumiya",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1248/112352l.webp",
    year: 2010,
  },
  "anilist:anime:2001": {
    title: "Gurren Lagann",
    posterUrl: "https://cdn.myanimelist.net/images/anime/4/5123l.webp",
    year: 2007,
  },
  "anilist:anime:4107": {
    title: "Gurren Lagann The Movie: Childhood's End",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1270/115752l.webp",
    year: 2008,
  },
  "anilist:anime:4565": {
    title: "Gurren Lagann The Movie: The Lights in the Sky are Stars",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/19698l.webp",
    year: 2009,
  },
  "anilist:anime:38000": {
    title: "Demon Slayer: Kimetsu no Yaiba",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1286/99889l.webp",
    year: 2019,
  },
  "anilist:anime:49926": {
    title: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1065/118763l.webp",
    year: 2021,
  },
  "anilist:anime:47778": {
    title: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1908/120036l.webp",
    year: 2022,
  },
  "anilist:anime:51019": {
    title: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1765/135099l.webp",
    year: 2023,
  },
  "anilist:anime:55701": {
    title: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1565/142711l.webp",
    year: 2024,
  },
  "anilist:anime:40748": {
    title: "Jujutsu Kaisen",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1171/109222l.webp",
    year: 2020,
  },
  "anilist:anime:48561": {
    title: "Jujutsu Kaisen 0",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1121/119044l.webp",
    year: 2021,
  },
  "anilist:anime:51009": {
    title: "Jujutsu Kaisen Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1792/138022l.webp",
    year: 2023,
  },
  "anilist:anime:11757": {
    title: "Sword Art Online",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/39717l.webp",
    year: 2012,
  },
  "anilist:anime:21881": {
    title: "Sword Art Online II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1223/121999l.webp",
    year: 2014,
  },
  "anilist:anime:31765": {
    title: "Sword Art Online the Movie: Ordinal Scale",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1557/123313l.webp",
    year: 2017,
  },
  "anilist:anime:36474": {
    title: "Sword Art Online: Alicization",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1993/93837l.webp",
    year: 2018,
  },
  "anilist:anime:39597": {
    title: "Sword Art Online: Alicization - War of Underworld",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1630/103417l.webp",
    year: 2019,
  },
  "anilist:anime:40540": {
    title: "Sword Art Online: Alicization - War of Underworld Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1438/105106l.webp",
    year: 2020,
  },
  "anilist:anime:42916": {
    title: "Sword Art Online the Movie: Progressive - Aria of a Starless Night",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1590/116274l.webp",
    year: 2021,
  },
  "anilist:anime:50275": {
    title: "Sword Art Online the Movie: Progressive - Scherzo of Deep Night",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1656/126446l.webp",
    year: 2022,
  },
  "anilist:anime:16498": {
    title: "Attack on Titan",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/47347l.webp",
    year: 2013,
  },
  "anilist:anime:25777": {
    title: "Attack on Titan Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/4/84177l.webp",
    year: 2017,
  },
  "anilist:anime:35760": {
    title: "Attack on Titan Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1173/92110l.webp",
    year: 2018,
  },
  "anilist:anime:38524": {
    title: "Attack on Titan Season 3 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1517/100633l.webp",
    year: 2019,
  },
  "anilist:anime:40028": {
    title: "Attack on Titan: Final Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1000/110531l.webp",
    year: 2021,
  },
  "anilist:anime:48583": {
    title: "Attack on Titan: Final Season Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1948/120625l.webp",
    year: 2022,
  },
  "anilist:anime:51535": {
    title: "Attack on Titan: Final Season - The Final Chapters",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1279/131078l.webp",
    year: 2023,
  },
  "anilist:anime:9253": {
    title: "Steins;Gate",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1935/127974l.webp",
    year: 2011,
  },
  "anilist:anime:30484": {
    title: "Steins;Gate 0",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1375/93521l.webp",
    year: 2018,
  },
  "anilist:anime:11577": {
    title: "Steins;Gate: The Movie - Load Region of Déjà Vu",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1611/112806l.webp",
    year: 2013,
  },
  "anilist:anime:20": {
    title: "Naruto",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1141/142503l.webp",
    year: 2002,
  },
  "anilist:anime:1735": {
    title: "Naruto Shippuden",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1565/111305l.webp",
    year: 2007,
  },
  "anilist:anime:16870": {
    title: "Naruto Shippuden the Movie 7: The Last",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1491/134498l.webp",
    year: 2014,
  },
  "anilist:anime:34566": {
    title: "Boruto: Naruto Next Generations",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1091/99847l.webp",
    year: 2017,
  },
  "anilist:anime:223": {
    title: "Dragon Ball",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1887/92364l.webp",
    year: 1986,
  },
  "anilist:anime:813": {
    title: "Dragon Ball Z",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1277/142022l.webp",
    year: 1989,
  },
  "anilist:anime:14837": {
    title: "Dragon Ball Z: Battle of Gods",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1734/93678l.webp",
    year: 2013,
  },
  "anilist:anime:25389": {
    title: "Dragon Ball Z: Resurrection 'F'",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1833/93679l.webp",
    year: 2015,
  },
  "anilist:anime:30694": {
    title: "Dragon Ball Super",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/74606l.webp",
    year: 2015,
  },
  "anilist:anime:36946": {
    title: "Dragon Ball Super: Broly",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1575/93498l.webp",
    year: 2018,
  },
  "anilist:anime:48903": {
    title: "Dragon Ball Super: Super Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1501/122797l.webp",
    year: 2022,
  },
  "anilist:anime:269": {
    title: "Bleach",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1541/147774l.webp",
    year: 2004,
  },
  "anilist:anime:41467": {
    title: "Bleach: Thousand-Year Blood War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1908/135431l.webp",
    year: 2022,
  },
  "anilist:anime:53998": {
    title: "Bleach: Thousand-Year Blood War - The Separation",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1164/138058l.webp",
    year: 2023,
  },
  "anilist:anime:56784": {
    title: "Bleach: Thousand-Year Blood War - The Conflict",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1595/144074l.webp",
    year: 2024,
  },
  "anilist:anime:60636": {
    title: "Bleach: Thousand-Year Blood War - The Calamity",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1653/154517l.webp",
    year: 2026,
  },
  "anilist:anime:1686": {
    title: "Bleach the Movie: Memories of Nobody",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1834/134488l.webp",
    year: 2006,
  },
  "anilist:anime:2889": {
    title: "Bleach the Movie: The DiamondDust Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1502/134489l.webp",
    year: 2007,
  },
  "anilist:anime:4835": {
    title: "Bleach the Movie: Fade to Black",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1633/134491l.webp",
    year: 2008,
  },
  "anilist:anime:8247": {
    title: "Bleach the Movie: Hell Verse",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1554/134492l.webp",
    year: 2010,
  },
  "anilist:anime:31964": {
    title: "My Hero Academia",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/78745l.webp",
    year: 2016,
  },
  "anilist:anime:33486": {
    title: "My Hero Academia Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/85221l.webp",
    year: 2017,
  },
  "anilist:anime:36896": {
    title: "My Hero Academia: Two Heroes",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1736/93138l.webp",
    year: 2018,
  },
  "anilist:anime:36456": {
    title: "My Hero Academia Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1319/92084l.webp",
    year: 2018,
  },
  "anilist:anime:38408": {
    title: "My Hero Academia Season 4",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1412/107914l.webp",
    year: 2019,
  },
  "anilist:anime:39565": {
    title: "My Hero Academia: Heroes Rising",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1019/103292l.webp",
    year: 2019,
  },
  "anilist:anime:41587": {
    title: "My Hero Academia Season 5",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1911/113611l.webp",
    year: 2021,
  },
  "anilist:anime:44200": {
    title: "My Hero Academia: World Heroes' Mission",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1049/115605l.webp",
    year: 2021,
  },
  "anilist:anime:49918": {
    title: "My Hero Academia Season 6",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1483/126005l.webp",
    year: 2022,
  },
  "anilist:anime:54789": {
    title: "My Hero Academia Season 7",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1573/157212l.webp",
    year: 2024,
  },
  "anilist:anime:31240": {
    title: "Re:ZERO -Starting Life in Another World-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1522/128039l.webp",
    year: 2016,
  },
  "anilist:anime:36286": {
    title: "Re:ZERO -Starting Life in Another World- Memory Snow",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1081/95707l.webp",
    year: 2018,
  },
  "anilist:anime:38414": {
    title: "Re:ZERO -Starting Life in Another World- The Frozen Bond",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1238/104023l.webp",
    year: 2019,
  },
  "anilist:anime:39587": {
    title: "Re:ZERO -Starting Life in Another World- Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1444/108005l.webp",
    year: 2020,
  },
  "anilist:anime:42203": {
    title: "Re:ZERO -Starting Life in Another World- Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1724/117421l.webp",
    year: 2021,
  },
  "anilist:anime:32182": {
    title: "Mob Psycho 100",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/80356l.webp",
    year: 2016,
  },
  "anilist:anime:36616": {
    title: "Mob Psycho 100 Reigen: The Miraculous Unknown Psychic",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/89331l.webp",
    year: 2018,
  },
  "anilist:anime:37510": {
    title: "Mob Psycho 100 II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1918/96303l.webp",
    year: 2019,
  },
  "anilist:anime:50172": {
    title: "Mob Psycho 100 III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1228/125011l.webp",
    year: 2022,
  },
  "anilist:anime:39535": {
    title: "Mushoku Tensei: Jobless Reincarnation",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1530/117776l.webp",
    year: 2021,
  },
  "anilist:anime:45576": {
    title: "Mushoku Tensei: Jobless Reincarnation Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1028/117777l.webp",
    year: 2021,
  },
  "anilist:anime:50360": {
    title: "Mushoku Tensei: Jobless Reincarnation - Eris the Goblin Slayer",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1094/120148l.webp",
    year: 2022,
  },
  "anilist:anime:55818": {
    title: 'Mushoku Tensei: Jobless Reincarnation Season 2 - Episode 0 "Guardian Fitz"',
    posterUrl: "https://cdn.myanimelist.net/images/anime/1627/136934l.webp",
    year: 2023,
  },
  "anilist:anime:51179": {
    title: "Mushoku Tensei: Jobless Reincarnation Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1898/138005l.webp",
    year: 2023,
  },
  "anilist:anime:55888": {
    title: "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1876/141251l.webp",
    year: 2024,
  },
  "anilist:anime:4654": {
    title: "A Certain Magical Index",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/75533l.webp",
    year: 2008,
  },
  "anilist:anime:6213": {
    title: "A Certain Scientific Railgun",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1099/106939l.webp",
    year: 2009,
  },
  "anilist:anime:8937": {
    title: "A Certain Magical Index II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/75612l.webp",
    year: 2010,
  },
  "anilist:anime:16049": {
    title: "A Certain Scientific Railgun S",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1429/152870l.webp",
    year: 2013,
  },
  "anilist:anime:11743": {
    title: "A Certain Magical Index the Movie: The Miracle of Endymion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1885/93861l.webp",
    year: 2013,
  },
  "anilist:anime:36432": {
    title: "A Certain Magical Index III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1583/93857l.webp",
    year: 2018,
  },
  "anilist:anime:38480": {
    title: "A Certain Scientific Accelerator",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1160/99995l.webp",
    year: 2019,
  },
  "anilist:anime:38481": {
    title: "A Certain Scientific Railgun T",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1819/103287l.webp",
    year: 2020,
  },
  "anilist:anime:43": {
    title: "Ghost in the Shell",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/82594l.webp",
    year: 1995,
  },
  "anilist:anime:467": {
    title: "Ghost in the Shell: Stand Alone Complex",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/50857l.webp",
    year: 2002,
  },
  "anilist:anime:801": {
    title: "Ghost in the Shell: Stand Alone Complex 2nd GIG",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1646/135390l.webp",
    year: 2004,
  },
  "anilist:anime:1566": {
    title: "Ghost in the Shell: Stand Alone Complex - Solid State Society",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/85128l.webp",
    year: 2006,
  },
  "anilist:anime:38799": {
    title: "Ghost in the Shell: SAC_2045",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1213/106702l.webp",
    year: 2020,
  },
  "anilist:anime:41750": {
    title: "Ghost in the Shell: SAC_2045 Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1591/121960l.webp",
    year: 2022,
  },
  "anilist:anime:14719": {
    title: "JoJo's Bizarre Adventure (2012)",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/40409l.webp",
    year: 2012,
  },
  "anilist:anime:20899": {
    title: "JoJo's Bizarre Adventure: Stardust Crusaders",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/55267l.webp",
    year: 2014,
  },
  "anilist:anime:26055": {
    title: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/75045l.webp",
    year: 2015,
  },
  "anilist:anime:31933": {
    title: "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/79156l.webp",
    year: 2016,
  },
  "anilist:anime:37991": {
    title: "JoJo's Bizarre Adventure: Golden Wind",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1882/94989l.webp",
    year: 2018,
  },
  "anilist:anime:48661": {
    title: "JoJo's Bizarre Adventure: Stone Ocean",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1896/119844l.webp",
    year: 2021,
  },
  "anilist:anime:51367": {
    title: "JoJo's Bizarre Adventure: Stone Ocean Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1051/121959l.webp",
    year: 2022,
  },
  "anilist:anime:53273": {
    title: "JoJo's Bizarre Adventure: Stone Ocean Part 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1233/128920l.webp",
    year: 2022,
  },
  "anilist:anime:30831": {
    title: "KonoSuba: God's Blessing on This Wonderful World!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1895/142748l.webp",
    year: 2016,
  },
  "anilist:anime:32937": {
    title: "KonoSuba: God's Blessing on This Wonderful World! 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/83188l.webp",
    year: 2017,
  },
  "anilist:anime:38040": {
    title: "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1638/119321l.webp",
    year: 2019,
  },
  "anilist:anime:49458": {
    title: "KonoSuba: God's Blessing on This Wonderful World! 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1758/141268l.webp",
    year: 2024,
  },
  "anilist:anime:29803": {
    title: "Overlord",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1945/136600l.webp",
    year: 2015,
  },
  "anilist:anime:35073": {
    title: "Overlord II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1212/113415l.webp",
    year: 2018,
  },
  "anilist:anime:37675": {
    title: "Overlord III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1511/93473l.webp",
    year: 2018,
  },
  "anilist:anime:34161": {
    title: "Overlord: The Undead King",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/87759l.webp",
    year: 2017,
  },
  "anilist:anime:34428": {
    title: "Overlord: The Dark Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/87758l.webp",
    year: 2017,
  },
  "anilist:anime:48895": {
    title: "Overlord IV",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1530/120110l.webp",
    year: 2022,
  },
  "anilist:anime:35790": {
    title: "The Rising of the Shield Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1490/101365l.webp",
    year: 2019,
  },
  "anilist:anime:40356": {
    title: "The Rising of the Shield Hero Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1143/121873l.webp",
    year: 2022,
  },
  "anilist:anime:40357": {
    title: "The Rising of the Shield Hero Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1317/139802l.webp",
    year: 2023,
  },
  "anilist:anime:37430": {
    title: "That Time I Got Reincarnated as a Slime",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1069/123309l.webp",
    year: 2018,
  },
  "anilist:anime:39551": {
    title: "That Time I Got Reincarnated as a Slime Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1271/109841l.webp",
    year: 2021,
  },
  "anilist:anime:41487": {
    title: "That Time I Got Reincarnated as a Slime Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1033/118296l.webp",
    year: 2021,
  },
  "anilist:anime:49877": {
    title: "That Time I Got Reincarnated as a Slime: The Movie - Scarlet Bond",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1745/128238l.webp",
    year: 2022,
  },
  "anilist:anime:53580": {
    title: "That Time I Got Reincarnated as a Slime Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1211/143476l.webp",
    year: 2024,
  },
  "anilist:anime:34599": {
    title: "Made in Abyss",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/86733l.webp",
    year: 2017,
  },
  "anilist:anime:36862": {
    title: "Made in Abyss: Dawn of the Deep Soul",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1803/117183l.webp",
    year: 2020,
  },
  "anilist:anime:41084": {
    title: "Made in Abyss: The Golden City of the Scorching Sun",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1864/122519l.webp",
    year: 2022,
  },
  "anilist:anime:33352": {
    title: "Violet Evergarden",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1795/95088l.webp",
    year: 2018,
  },
  "anilist:anime:39741": {
    title: "Violet Evergarden: Eternity and the Auto Memory Doll",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1667/112943l.webp",
    year: 2019,
  },
  "anilist:anime:37987": {
    title: "Violet Evergarden: The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1825/110716l.webp",
    year: 2020,
  },
  "anilist:anime:5680": {
    title: "K-ON!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/76120l.webp",
    year: 2009,
  },
  "anilist:anime:7791": {
    title: "K-ON! Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/76121l.webp",
    year: 2010,
  },
  "anilist:anime:9617": {
    title: "K-ON! The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/76233l.webp",
    year: 2011,
  },
  "anilist:anime:13601": {
    title: "Psycho-Pass",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1314/142015l.webp",
    year: 2012,
  },
  "anilist:anime:23281": {
    title: "Psycho-Pass 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1197/100616l.webp",
    year: 2014,
  },
  "anilist:anime:21339": {
    title: "Psycho-Pass: The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/71793l.webp",
    year: 2015,
  },
  "anilist:anime:52747": {
    title: "Psycho-Pass: Providence",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1244/134653l.webp",
    year: 2023,
  },
  "anilist:anime:39491": {
    title: "Psycho-Pass 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1406/104344l.webp",
    year: 2019,
  },
  "anilist:anime:40858": {
    title: "Psycho-Pass 3: First Inspector",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1085/110722l.webp",
    year: 2020,
  },
  "anilist:anime:22319": {
    title: "Tokyo Ghoul",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1498/134443l.webp",
    year: 2014,
  },
  "anilist:anime:27899": {
    title: "Tokyo Ghoul √A",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1889/123307l.webp",
    year: 2015,
  },
  "anilist:anime:36511": {
    title: "Tokyo Ghoul:re",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1063/95086l.webp",
    year: 2018,
  },
  "anilist:anime:37799": {
    title: "Tokyo Ghoul:re 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1545/121995l.webp",
    year: 2018,
  },
  "anilist:anime:44511": {
    title: "Chainsaw Man",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1806/126216l.webp",
    year: 2022,
  },
  "anilist:anime:57555": {
    title: "Chainsaw Man – The Movie: Reze Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1763/150638l.webp",
    year: 2025,
  },
  "anilist:anime:50265": {
    title: "Spy x Family",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1441/122795l.webp",
    year: 2022,
  },
  "anilist:anime:50602": {
    title: "Spy x Family Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1111/127508l.webp",
    year: 2022,
  },
  "anilist:anime:53887": {
    title: "Spy x Family Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1506/138982l.webp",
    year: 2023,
  },
  "anilist:anime:53888": {
    title: "Spy x Family Code: White",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1426/139388l.webp",
    year: 2023,
  },
  "anilist:anime:37521": {
    title: "Vinland Saga",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1500/103005l.webp",
    year: 2019,
  },
  "anilist:anime:49387": {
    title: "Vinland Saga Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1170/124312l.webp",
    year: 2023,
  },
  "anilist:anime:38691": {
    title: "Dr. Stone",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1613/102576l.webp",
    year: 2019,
  },
  "anilist:anime:40852": {
    title: "Dr. Stone: Stone Wars",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1711/110614l.webp",
    year: 2021,
  },
  "anilist:anime:50612": {
    title: "Dr. Stone: Ryusui",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1071/124921l.webp",
    year: 2022,
  },
  "anilist:anime:48549": {
    title: "Dr. Stone: New World",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1316/136268l.webp",
    year: 2023,
  },
  "anilist:anime:55644": {
    title: "Dr. Stone: New World Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1236/138696l.webp",
    year: 2023,
  },
  "anilist:anime:57592": {
    title: "Dr. Stone: Science Future",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1403/146479l.webp",
    year: 2025,
  },
  "anilist:anime:61322": {
    title: "Dr. Stone: Science Future Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1785/151710l.webp",
    year: 2025,
  },
  "anilist:anime:37779": {
    title: "The Promised Neverland",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1830/118780l.webp",
    year: 2019,
  },
  "anilist:anime:39617": {
    title: "The Promised Neverland Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1815/110626l.webp",
    year: 2021,
  },
  "anilist:anime:47616": {
    title: "The Promised Neverland: Guidepost",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1097/111813l.webp",
    year: 2021,
  },
  "anilist:anime:20583": {
    title: "Haikyu!!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/76014l.webp",
    year: 2014,
  },
  "anilist:anime:28891": {
    title: "Haikyu!! 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/76662l.webp",
    year: 2015,
  },
  "anilist:anime:32935": {
    title: "Haikyu!! 3rd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/81992l.webp",
    year: 2016,
  },
  "anilist:anime:38883": {
    title: "Haikyu!! To the Top",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1813/105367l.webp",
    year: 2020,
  },
  "anilist:anime:40776": {
    title: "Haikyu!! To the Top 2nd-cour",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1453/106768l.webp",
    year: 2020,
  },
  "anilist:anime:52742": {
    title: "Haikyu!! Movie: The Dumpster Battle",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1665/140360l.webp",
    year: 2024,
  },
  "anilist:anime:37999": {
    title: "Kaguya-sama: Love is War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1295/106551l.webp",
    year: 2019,
  },
  "anilist:anime:40591": {
    title: "Kaguya-sama: Love is War?",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1764/106659l.webp",
    year: 2020,
  },
  "anilist:anime:43608": {
    title: "Kaguya-sama: Love is War -Ultra Romantic-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1160/122627l.webp",
    year: 2022,
  },
  "anilist:anime:52198": {
    title: "Kaguya-sama: Love is War -The First Kiss That Never Ends-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1670/130060l.webp",
    year: 2022,
  },
  "anilist:anime:37450": {
    title: "Rascal Does Not Dream of Bunny Girl Senpai",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1301/93586l.webp",
    year: 2018,
  },
  "anilist:anime:38329": {
    title: "Rascal Does Not Dream of a Dreaming Girl",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1613/102179l.webp",
    year: 2019,
  },
  "anilist:anime:53129": {
    title: "Rascal Does Not Dream of a Sister Venturing Out",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1540/134808l.webp",
    year: 2023,
  },
  "anilist:anime:54870": {
    title: "Rascal Does Not Dream of a Knapsack Kid",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1937/138379l.webp",
    year: 2023,
  },
  "anilist:anime:38680": {
    title: "Fruits Basket 1st Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1447/99827l.webp",
    year: 2019,
  },
  "anilist:anime:40417": {
    title: "Fruits Basket 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1972/111635l.webp",
    year: 2020,
  },
  "anilist:anime:42938": {
    title: "Fruits Basket: The Final Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1085/114792l.webp",
    year: 2021,
  },
  "anilist:anime:49310": {
    title: "Fruits Basket: Prelude",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1034/120096l.webp",
    year: 2022,
  },
  "anilist:anime:23755": {
    title: "The Seven Deadly Sins",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/65409l.webp",
    year: 2014,
  },
  "anilist:anime:31722": {
    title: "The Seven Deadly Sins: Signs of Holy War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/79331l.webp",
    year: 2016,
  },
  "anilist:anime:34577": {
    title: "The Seven Deadly Sins: Revival of the Commandments",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/90089l.webp",
    year: 2018,
  },
  "anilist:anime:35946": {
    title: "The Seven Deadly Sins the Movie: Prisoners of the Sky",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1444/91899l.webp",
    year: 2018,
  },
  "anilist:anime:39701": {
    title: "The Seven Deadly Sins: Imperial Wrath of the Gods",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1546/103418l.webp",
    year: 2019,
  },
  "anilist:anime:41491": {
    title: "The Seven Deadly Sins: Dragon's Judgement",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1011/111551l.webp",
    year: 2021,
  },
  "anilist:anime:46420": {
    title: "The Seven Deadly Sins the Movie 2: Cursed By Light",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1096/113360l.webp",
    year: 2021,
  },
  "anilist:anime:15583": {
    title: "Date A Live",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/44844l.webp",
    year: 2013,
  },
  "anilist:anime:19163": {
    title: "Date A Live II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1690/141818l.webp",
    year: 2014,
  },
  "anilist:anime:24655": {
    title: "Date A Live Movie: Mayuri Judgement",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/75466l.webp",
    year: 2015,
  },
  "anilist:anime:36633": {
    title: "Date A Live III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1055/100468l.webp",
    year: 2019,
  },
  "anilist:anime:41461": {
    title: "Date A Live IV",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1368/121281l.webp",
    year: 2022,
  },
  "anilist:anime:52196": {
    title: "Date A Live V",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1659/141438l.webp",
    year: 2024,
  },
  "anilist:anime:2167": {
    title: "Clannad",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1804/95033l.webp",
    year: 2007,
  },
  "anilist:anime:4181": {
    title: "Clannad: After Story",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1299/110774l.webp",
    year: 2008,
  },
  "anilist:anime:4059": {
    title: "Clannad: Another World, Tomoyo Chapter",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/19620l.webp",
    year: 2008,
  },
  "anilist:anime:6351": {
    title: "Clannad: After Story - Another World, Kyou Chapter",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/19621l.webp",
    year: 2009,
  },
  "anilist:anime:1723": {
    title: "Clannad The Motion Picture",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/75650l.webp",
    year: 2007,
  },
  "anilist:anime:38101": {
    title: "The Quintessential Quintuplets",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1819/97947l.webp",
    year: 2019,
  },
  "anilist:anime:39783": {
    title: "The Quintessential Quintuplets 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1775/109514l.webp",
    year: 2021,
  },
  "anilist:anime:48548": {
    title: "The Quintessential Quintuplets Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1037/122516l.webp",
    year: 2022,
  },
};
