// AUTO-GENERATED by scripts/resolve-franchise-data.mjs — do not edit by hand.
// Card data (title, poster, year) for every entry of every curated franchise,
// keyed by `${source}:${kind}:${sourceId}`. Pre-resolved so getWatchOrder and
// the /watch-order index render curated sagas with zero TMDB/Jikan calls at
// request time. Regenerate when curated-franchises.ts changes.

export type CuratedEntryData = { title: string; posterUrl: string | null; year: number | null };

export const FRANCHISE_ENTRY_DATA: Record<string, CuratedEntryData> = {
  "tmdb:movie:1771": {
    title: "Capitán América: El primer vengador",
    posterUrl: "https://image.tmdb.org/t/p/w342/i5eSA5DK5iAv53SB4yv57bN56o6.jpg",
    year: 2011,
  },
  "tmdb:movie:299537": {
    title: "Capitana Marvel",
    posterUrl: "https://image.tmdb.org/t/p/w342/5SPa7dZ85p54xa7E9tHRmfKq5ce.jpg",
    year: 2019,
  },
  "tmdb:movie:1726": {
    title: "Iron Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/tFCTNx7foAsUQpgu2x1KjAJD1wT.jpg",
    year: 2008,
  },
  "tmdb:movie:10138": {
    title: "Iron Man 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/ayyJVOV5I4MGjti7nIHC3mVCagR.jpg",
    year: 2010,
  },
  "tmdb:movie:1724": {
    title: "El increíble Hulk",
    posterUrl: "https://image.tmdb.org/t/p/w342/rCTSJzsU2GkH5uLwP1RFb3OjtLs.jpg",
    year: 2008,
  },
  "tmdb:movie:10195": {
    title: "Thor",
    posterUrl: "https://image.tmdb.org/t/p/w342/qFAVW4XJaxhj7PcpiUI5hhO9bOX.jpg",
    year: 2011,
  },
  "tmdb:movie:24428": {
    title: "Los Vengadores",
    posterUrl: "https://image.tmdb.org/t/p/w342/ugX4WZJO3jEvTOerctAWJLinujo.jpg",
    year: 2012,
  },
  "tmdb:movie:68721": {
    title: "Iron Man 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/cW0fOIZONkgeiMJDYzqUcgl4MUn.jpg",
    year: 2013,
  },
  "tmdb:movie:76338": {
    title: "Thor: el mundo oscuro",
    posterUrl: "https://image.tmdb.org/t/p/w342/cs5YLwGBCJBold74avD3NecO5Zc.jpg",
    year: 2013,
  },
  "tmdb:movie:100402": {
    title: "Capitán América: El soldado de invierno",
    posterUrl: "https://image.tmdb.org/t/p/w342/3Zv12uAqBxj4xAdeHeVySEQzY1o.jpg",
    year: 2014,
  },
  "tmdb:movie:118340": {
    title: "Guardianes de la galaxia",
    posterUrl: "https://image.tmdb.org/t/p/w342/zqZNnuMtrmK99Xux91KiCdnZxgb.jpg",
    year: 2014,
  },
  "tmdb:movie:283995": {
    title: "Guardianes de la Galaxia Vol. 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/kdg6Y06jfq9FV7qknWNcKLYtBJn.jpg",
    year: 2017,
  },
  "tmdb:movie:99861": {
    title: "Vengadores: La era de Ultrón",
    posterUrl: "https://image.tmdb.org/t/p/w342/3Lz6h5rlCFNNyCZRaRJ2ZjtBnAE.jpg",
    year: 2015,
  },
  "tmdb:movie:102899": {
    title: "Ant-Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/zwuE28gSXlLFLgueqMe9b7xKy1f.jpg",
    year: 2015,
  },
  "tmdb:movie:271110": {
    title: "Capitán América: Civil War",
    posterUrl: "https://image.tmdb.org/t/p/w342/jPPy7tCfglppQo6J9nGwU6UmJ8X.jpg",
    year: 2016,
  },
  "tmdb:movie:497698": {
    title: "Viuda Negra",
    posterUrl: "https://image.tmdb.org/t/p/w342/uR3ex7LZrX3lbIMNb87WBXzCWM.jpg",
    year: 2021,
  },
  "tmdb:movie:315635": {
    title: "Spider-Man: Homecoming",
    posterUrl: "https://image.tmdb.org/t/p/w342/yJfPC6pjSJ5VOsVyXhx5PXBe0mR.jpg",
    year: 2017,
  },
  "tmdb:movie:284052": {
    title: "Doctor Strange",
    posterUrl: "https://image.tmdb.org/t/p/w342/wJEZI3PWyMW7qcW6n9jyCh7Cclf.jpg",
    year: 2016,
  },
  "tmdb:movie:284054": {
    title: "Black Panther",
    posterUrl: "https://image.tmdb.org/t/p/w342/lAPzezdc5E6DFnttJwCWXZ9A9C6.jpg",
    year: 2018,
  },
  "tmdb:movie:284053": {
    title: "Thor: Ragnarok",
    posterUrl: "https://image.tmdb.org/t/p/w342/pGtkLdk4rnF2A3Yz2BHiTgRwMU4.jpg",
    year: 2017,
  },
  "tmdb:movie:363088": {
    title: "Ant-Man y la Avispa",
    posterUrl: "https://image.tmdb.org/t/p/w342/bvYI6i9lQ3bsup9PgnMF3YYr8ZR.jpg",
    year: 2018,
  },
  "tmdb:movie:299536": {
    title: "Vengadores: Infinity War",
    posterUrl: "https://image.tmdb.org/t/p/w342/ksBQ4oHQDdJwND8H90ay8CbMihU.jpg",
    year: 2018,
  },
  "tmdb:movie:299534": {
    title: "Vengadores: Endgame",
    posterUrl: "https://image.tmdb.org/t/p/w342/br6krBFpaYmCSglLBWRuhui7tPc.jpg",
    year: 2019,
  },
  "tmdb:movie:429617": {
    title: "Spider-Man: Lejos de casa",
    posterUrl: "https://image.tmdb.org/t/p/w342/o59zDVJDIehGcWZsMUGU5SN0V0D.jpg",
    year: 2019,
  },
  "tmdb:movie:1893": {
    title: "La guerra de las galaxias. Episodio I: La amenaza fantasma",
    posterUrl: "https://image.tmdb.org/t/p/w342/4rjatbWmGGmu0DZs6WNpXaUWqWN.jpg",
    year: 1999,
  },
  "tmdb:movie:1894": {
    title: "La guerra de las galaxias. Episodio II: El ataque de los clones",
    posterUrl: "https://image.tmdb.org/t/p/w342/pwwBIUqVSWrCBuUAvbaNdf7VajF.jpg",
    year: 2002,
  },
  "tmdb:movie:1895": {
    title: "La guerra de las galaxias. Episodio III: La venganza de los Sith",
    posterUrl: "https://image.tmdb.org/t/p/w342/5dj0ERxM8NxoiWBdlY6TT9PJmKi.jpg",
    year: 2005,
  },
  "tmdb:movie:11": {
    title: "La guerra de las galaxias",
    posterUrl: "https://image.tmdb.org/t/p/w342/ahT4ObS7XKedQkOSpGr1wQ97aKA.jpg",
    year: 1977,
  },
  "tmdb:movie:1891": {
    title: "El imperio contraataca",
    posterUrl: "https://image.tmdb.org/t/p/w342/eU7KcNAOeZj9PBIcGUMSsuJz8qj.jpg",
    year: 1980,
  },
  "tmdb:movie:1892": {
    title: "El retorno del Jedi",
    posterUrl: "https://image.tmdb.org/t/p/w342/rKMmXzdm7eRgmlwYo7iq3klT7wJ.jpg",
    year: 1983,
  },
  "tmdb:movie:140607": {
    title: "Star Wars: El despertar de la fuerza",
    posterUrl: "https://image.tmdb.org/t/p/w342/vI86GLIkT5pP3ZfNs2EvmTrBLBm.jpg",
    year: 2015,
  },
  "tmdb:movie:181808": {
    title: "Star Wars: Los últimos Jedi",
    posterUrl: "https://image.tmdb.org/t/p/w342/7SNzh1fY3YJ8Y8MX93pZF5cJHaH.jpg",
    year: 2017,
  },
  "tmdb:movie:181812": {
    title: "Star Wars: El ascenso de Skywalker",
    posterUrl: "https://image.tmdb.org/t/p/w342/oeQxq6If4DcW6ADIYCF9SQwKov.jpg",
    year: 2019,
  },
  "anilist:anime:10087": {
    title: "Fate/Zero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1887/117644l.webp",
    year: 2011,
  },
  "anilist:anime:11741": {
    title: "Fate/Zero Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1522/117645l.webp",
    year: 2012,
  },
  "anilist:anime:22297": {
    title: "Fate/stay night [Unlimited Blade Works]",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/67333l.webp",
    year: 2014,
  },
  "anilist:anime:28701": {
    title: "Fate/stay night [Unlimited Blade Works] Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1881/124810l.webp",
    year: 2015,
  },
  "anilist:anime:25537": {
    title: "Fate/stay night: Heaven's Feel - I. Presage Flower",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1274/102213l.webp",
    year: 2017,
  },
  "anilist:anime:33049": {
    title: "Fate/stay night: Heaven's Feel - II. Lost Butterfly",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1974/98158l.webp",
    year: 2019,
  },
  "anilist:anime:33050": {
    title: "Fate/stay night: Heaven's Feel - III. Spring Song",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1142/112957l.webp",
    year: 2020,
  },
  "anilist:anime:5081": {
    title: "Bakemonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/75274l.webp",
    year: 2009,
  },
  "anilist:anime:9260": {
    title: "Kizumonogatari Part 1: Iron-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1783/112810l.webp",
    year: 2016,
  },
  "anilist:anime:31757": {
    title: "Kizumonogatari Part 2: Hot-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1981/112812l.webp",
    year: 2016,
  },
  "anilist:anime:31758": {
    title: "Kizumonogatari Part 3: Cold-Blooded",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1084/112813l.webp",
    year: 2017,
  },
  "anilist:anime:11597": {
    title: "Nisemonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1044/103654l.webp",
    year: 2012,
  },
  "anilist:anime:15689": {
    title: "Nekomonogatari Black",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1170/121597l.webp",
    year: 2012,
  },
  "anilist:anime:17074": {
    title: "Monogatari Series: Second Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1807/121534l.webp",
    year: 2013,
  },
  "anilist:anime:21855": {
    title: "Hanamonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/65755l.webp",
    year: 2014,
  },
  "anilist:anime:28025": {
    title: "Tsukimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/68259l.webp",
    year: 2014,
  },
  "anilist:anime:31181": {
    title: "Owarimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/76479l.webp",
    year: 2015,
  },
  "anilist:anime:32268": {
    title: "Koyomimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/77744l.webp",
    year: 2016,
  },
  "anilist:anime:35247": {
    title: "Owarimonogatari Second Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/87322l.webp",
    year: 2017,
  },
  "anilist:anime:36999": {
    title: "Zoku Owarimonogatari",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1022/96168l.webp",
    year: 2019,
  },
  "anilist:anime:57864": {
    title: "Monogatari Series: Off & Monster Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1142/146776l.webp",
    year: 2024,
  },
  "anilist:anime:30": {
    title: "Neon Genesis Evangelion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1314/108941l.webp",
    year: 1995,
  },
  "anilist:anime:32": {
    title: "Neon Genesis Evangelion: The End of Evangelion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1404/98182l.webp",
    year: 1997,
  },
  "anilist:anime:2759": {
    title: "Evangelion: 1.0 You Are (Not) Alone",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/74975l.webp",
    year: 2007,
  },
  "anilist:anime:3784": {
    title: "Evangelion: 2.0 You Can (Not) Advance",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/74983l.webp",
    year: 2009,
  },
  "anilist:anime:3785": {
    title: "Evangelion: 3.0 You Can (Not) Redo",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/43201l.webp",
    year: 2012,
  },
  "anilist:anime:3786": {
    title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1422/113533l.webp",
    year: 2021,
  },
  "anilist:anime:9756": {
    title: "Puella Magi Madoka Magica",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/55225l.webp",
    year: 2011,
  },
  "anilist:anime:11977": {
    title: "Puella Magi Madoka Magica the Movie Part 1: Beginnings",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/42331l.webp",
    year: 2012,
  },
  "anilist:anime:11979": {
    title: "Puella Magi Madoka Magica the Movie Part 2: Eternal",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/42265l.webp",
    year: 2012,
  },
  "anilist:anime:11981": {
    title: "Puella Magi Madoka Magica the Movie: Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/54231l.webp",
    year: 2013,
  },
  "anilist:anime:1575": {
    title: "Code Geass: Lelouch of the Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1032/135088l.webp",
    year: 2006,
  },
  "anilist:anime:2904": {
    title: "Code Geass: Lelouch of the Rebellion R2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1088/135089l.webp",
    year: 2008,
  },
  "anilist:anime:34437": {
    title: "Code Geass: Lelouch of the Re;surrection",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1274/113436l.webp",
    year: 2019,
  },
  "anilist:anime:849": {
    title: "The Melancholy of Haruhi Suzumiya",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1470/137929l.webp",
    year: 2006,
  },
  "anilist:anime:4382": {
    title: "The Melancholy of Haruhi Suzumiya (2009)",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/75377l.webp",
    year: 2009,
  },
  "anilist:anime:7311": {
    title: "The Disappearance of Haruhi Suzumiya",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1248/112352l.webp",
    year: 2010,
  },
  "anilist:anime:2001": {
    title: "Gurren Lagann",
    posterUrl: "https://cdn.myanimelist.net/images/anime/4/5123l.webp",
    year: 2007,
  },
  "anilist:anime:4107": {
    title: "Gurren Lagann The Movie: Childhood's End",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1270/115752l.webp",
    year: 2008,
  },
  "anilist:anime:4565": {
    title: "Gurren Lagann The Movie: The Lights in the Sky are Stars",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/19698l.webp",
    year: 2009,
  },
  "anilist:anime:38000": {
    title: "Demon Slayer: Kimetsu no Yaiba",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1286/99889l.webp",
    year: 2019,
  },
  "anilist:anime:49926": {
    title: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1065/118763l.webp",
    year: 2021,
  },
  "anilist:anime:47778": {
    title: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1908/120036l.webp",
    year: 2022,
  },
  "anilist:anime:51019": {
    title: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1765/135099l.webp",
    year: 2023,
  },
  "anilist:anime:55701": {
    title: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1565/142711l.webp",
    year: 2024,
  },
  "anilist:anime:40748": {
    title: "Jujutsu Kaisen",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1171/109222l.webp",
    year: 2020,
  },
  "anilist:anime:48561": {
    title: "Jujutsu Kaisen 0",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1121/119044l.webp",
    year: 2021,
  },
  "anilist:anime:51009": {
    title: "Jujutsu Kaisen Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1792/138022l.webp",
    year: 2023,
  },
  "anilist:anime:11757": {
    title: "Sword Art Online",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/39717l.webp",
    year: 2012,
  },
  "anilist:anime:21881": {
    title: "Sword Art Online II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1223/121999l.webp",
    year: 2014,
  },
  "anilist:anime:31765": {
    title: "Sword Art Online the Movie: Ordinal Scale",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1557/123313l.webp",
    year: 2017,
  },
  "anilist:anime:36474": {
    title: "Sword Art Online: Alicization",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1993/93837l.webp",
    year: 2018,
  },
  "anilist:anime:39597": {
    title: "Sword Art Online: Alicization - War of Underworld",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1630/103417l.webp",
    year: 2019,
  },
  "anilist:anime:40540": {
    title: "Sword Art Online: Alicization - War of Underworld Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1438/105106l.webp",
    year: 2020,
  },
  "anilist:anime:42916": {
    title: "Sword Art Online the Movie: Progressive - Aria of a Starless Night",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1590/116274l.webp",
    year: 2021,
  },
  "anilist:anime:50275": {
    title: "Sword Art Online the Movie: Progressive - Scherzo of Deep Night",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1656/126446l.webp",
    year: 2022,
  },
  "anilist:anime:16498": {
    title: "Attack on Titan",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/47347l.webp",
    year: 2013,
  },
  "anilist:anime:25777": {
    title: "Attack on Titan Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/4/84177l.webp",
    year: 2017,
  },
  "anilist:anime:35760": {
    title: "Attack on Titan Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1173/92110l.webp",
    year: 2018,
  },
  "anilist:anime:38524": {
    title: "Attack on Titan Season 3 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1517/100633l.webp",
    year: 2019,
  },
  "anilist:anime:40028": {
    title: "Attack on Titan: Final Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1000/110531l.webp",
    year: 2021,
  },
  "anilist:anime:48583": {
    title: "Attack on Titan: Final Season Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1948/120625l.webp",
    year: 2022,
  },
  "anilist:anime:51535": {
    title: "Attack on Titan: Final Season - The Final Chapters",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1279/131078l.webp",
    year: 2023,
  },
  "anilist:anime:9253": {
    title: "Steins;Gate",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1935/127974l.webp",
    year: 2011,
  },
  "anilist:anime:30484": {
    title: "Steins;Gate 0",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1375/93521l.webp",
    year: 2018,
  },
  "anilist:anime:11577": {
    title: "Steins;Gate: The Movie - Load Region of Déjà Vu",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1611/112806l.webp",
    year: 2013,
  },
  "anilist:anime:20": {
    title: "Naruto",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1141/142503l.webp",
    year: 2002,
  },
  "anilist:anime:1735": {
    title: "Naruto Shippuden",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1565/111305l.webp",
    year: 2007,
  },
  "anilist:anime:16870": {
    title: "Naruto Shippuden the Movie 7: The Last",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1491/134498l.webp",
    year: 2014,
  },
  "anilist:anime:34566": {
    title: "Boruto: Naruto Next Generations",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1091/99847l.webp",
    year: 2017,
  },
  "anilist:anime:223": {
    title: "Dragon Ball",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1887/92364l.webp",
    year: 1986,
  },
  "anilist:anime:813": {
    title: "Dragon Ball Z",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1277/142022l.webp",
    year: 1989,
  },
  "anilist:anime:14837": {
    title: "Dragon Ball Z: Battle of Gods",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1734/93678l.webp",
    year: 2013,
  },
  "anilist:anime:25389": {
    title: "Dragon Ball Z: Resurrection 'F'",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1833/93679l.webp",
    year: 2015,
  },
  "anilist:anime:30694": {
    title: "Dragon Ball Super",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/74606l.webp",
    year: 2015,
  },
  "anilist:anime:36946": {
    title: "Dragon Ball Super: Broly",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1575/93498l.webp",
    year: 2018,
  },
  "anilist:anime:48903": {
    title: "Dragon Ball Super: Super Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1501/122797l.webp",
    year: 2022,
  },
  "anilist:anime:269": {
    title: "Bleach",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1541/147774l.webp",
    year: 2004,
  },
  "anilist:anime:41467": {
    title: "Bleach: Thousand-Year Blood War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1908/135431l.webp",
    year: 2022,
  },
  "anilist:anime:53998": {
    title: "Bleach: Thousand-Year Blood War - The Separation",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1164/138058l.webp",
    year: 2023,
  },
  "anilist:anime:56784": {
    title: "Bleach: Thousand-Year Blood War - The Conflict",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1595/144074l.webp",
    year: 2024,
  },
  "anilist:anime:60636": {
    title: "Bleach: Thousand-Year Blood War - The Calamity",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1653/154517l.webp",
    year: 2026,
  },
  "anilist:anime:1686": {
    title: "Bleach the Movie: Memories of Nobody",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1834/134488l.webp",
    year: 2006,
  },
  "anilist:anime:2889": {
    title: "Bleach the Movie: The DiamondDust Rebellion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1502/134489l.webp",
    year: 2007,
  },
  "anilist:anime:4835": {
    title: "Bleach the Movie: Fade to Black",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1633/134491l.webp",
    year: 2008,
  },
  "anilist:anime:8247": {
    title: "Bleach the Movie: Hell Verse",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1554/134492l.webp",
    year: 2010,
  },
  "anilist:anime:31964": {
    title: "My Hero Academia",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/78745l.webp",
    year: 2016,
  },
  "anilist:anime:33486": {
    title: "My Hero Academia Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/85221l.webp",
    year: 2017,
  },
  "anilist:anime:36896": {
    title: "My Hero Academia: Two Heroes",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1736/93138l.webp",
    year: 2018,
  },
  "anilist:anime:36456": {
    title: "My Hero Academia Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1319/92084l.webp",
    year: 2018,
  },
  "anilist:anime:38408": {
    title: "My Hero Academia Season 4",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1412/107914l.webp",
    year: 2019,
  },
  "anilist:anime:39565": {
    title: "My Hero Academia: Heroes Rising",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1019/103292l.webp",
    year: 2019,
  },
  "anilist:anime:41587": {
    title: "My Hero Academia Season 5",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1911/113611l.webp",
    year: 2021,
  },
  "anilist:anime:44200": {
    title: "My Hero Academia: World Heroes' Mission",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1049/115605l.webp",
    year: 2021,
  },
  "anilist:anime:49918": {
    title: "My Hero Academia Season 6",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1483/126005l.webp",
    year: 2022,
  },
  "anilist:anime:54789": {
    title: "My Hero Academia Season 7",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1573/157212l.webp",
    year: 2024,
  },
  "anilist:anime:31240": {
    title: "Re:ZERO -Starting Life in Another World-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1522/128039l.webp",
    year: 2016,
  },
  "anilist:anime:36286": {
    title: "Re:ZERO -Starting Life in Another World- Memory Snow",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1081/95707l.webp",
    year: 2018,
  },
  "anilist:anime:38414": {
    title: "Re:ZERO -Starting Life in Another World- The Frozen Bond",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1238/104023l.webp",
    year: 2019,
  },
  "anilist:anime:39587": {
    title: "Re:ZERO -Starting Life in Another World- Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1444/108005l.webp",
    year: 2020,
  },
  "anilist:anime:42203": {
    title: "Re:ZERO -Starting Life in Another World- Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1724/117421l.webp",
    year: 2021,
  },
  "anilist:anime:32182": {
    title: "Mob Psycho 100",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/80356l.webp",
    year: 2016,
  },
  "anilist:anime:36616": {
    title: "Mob Psycho 100 Reigen: The Miraculous Unknown Psychic",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/89331l.webp",
    year: 2018,
  },
  "anilist:anime:37510": {
    title: "Mob Psycho 100 II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1918/96303l.webp",
    year: 2019,
  },
  "anilist:anime:50172": {
    title: "Mob Psycho 100 III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1228/125011l.webp",
    year: 2022,
  },
  "anilist:anime:39535": {
    title: "Mushoku Tensei: Jobless Reincarnation",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1530/117776l.webp",
    year: 2021,
  },
  "anilist:anime:45576": {
    title: "Mushoku Tensei: Jobless Reincarnation Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1028/117777l.webp",
    year: 2021,
  },
  "anilist:anime:50360": {
    title: "Mushoku Tensei: Jobless Reincarnation - Eris the Goblin Slayer",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1094/120148l.webp",
    year: 2022,
  },
  "anilist:anime:55818": {
    title: 'Mushoku Tensei: Jobless Reincarnation Season 2 - Episode 0 "Guardian Fitz"',
    posterUrl: "https://cdn.myanimelist.net/images/anime/1627/136934l.webp",
    year: 2023,
  },
  "anilist:anime:51179": {
    title: "Mushoku Tensei: Jobless Reincarnation Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1898/138005l.webp",
    year: 2023,
  },
  "anilist:anime:55888": {
    title: "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1876/141251l.webp",
    year: 2024,
  },
  "anilist:anime:4654": {
    title: "A Certain Magical Index",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/75533l.webp",
    year: 2008,
  },
  "anilist:anime:6213": {
    title: "A Certain Scientific Railgun",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1099/106939l.webp",
    year: 2009,
  },
  "anilist:anime:8937": {
    title: "A Certain Magical Index II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/75612l.webp",
    year: 2010,
  },
  "anilist:anime:16049": {
    title: "A Certain Scientific Railgun S",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1429/152870l.webp",
    year: 2013,
  },
  "anilist:anime:11743": {
    title: "A Certain Magical Index the Movie: The Miracle of Endymion",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1885/93861l.webp",
    year: 2013,
  },
  "anilist:anime:36432": {
    title: "A Certain Magical Index III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1583/93857l.webp",
    year: 2018,
  },
  "anilist:anime:38480": {
    title: "A Certain Scientific Accelerator",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1160/99995l.webp",
    year: 2019,
  },
  "anilist:anime:38481": {
    title: "A Certain Scientific Railgun T",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1819/103287l.webp",
    year: 2020,
  },
  "anilist:anime:43": {
    title: "Ghost in the Shell",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/82594l.webp",
    year: 1995,
  },
  "anilist:anime:467": {
    title: "Ghost in the Shell: Stand Alone Complex",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/50857l.webp",
    year: 2002,
  },
  "anilist:anime:801": {
    title: "Ghost in the Shell: Stand Alone Complex 2nd GIG",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1646/135390l.webp",
    year: 2004,
  },
  "anilist:anime:1566": {
    title: "Ghost in the Shell: Stand Alone Complex - Solid State Society",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/85128l.webp",
    year: 2006,
  },
  "anilist:anime:38799": {
    title: "Ghost in the Shell: SAC_2045",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1213/106702l.webp",
    year: 2020,
  },
  "anilist:anime:41750": {
    title: "Ghost in the Shell: SAC_2045 Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1591/121960l.webp",
    year: 2022,
  },
  "anilist:anime:14719": {
    title: "JoJo's Bizarre Adventure (2012)",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/40409l.webp",
    year: 2012,
  },
  "anilist:anime:20899": {
    title: "JoJo's Bizarre Adventure: Stardust Crusaders",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/55267l.webp",
    year: 2014,
  },
  "anilist:anime:26055": {
    title: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/75045l.webp",
    year: 2015,
  },
  "anilist:anime:31933": {
    title: "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
    posterUrl: "https://cdn.myanimelist.net/images/anime/3/79156l.webp",
    year: 2016,
  },
  "anilist:anime:37991": {
    title: "JoJo's Bizarre Adventure: Golden Wind",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1882/94989l.webp",
    year: 2018,
  },
  "anilist:anime:48661": {
    title: "JoJo's Bizarre Adventure: Stone Ocean",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1896/119844l.webp",
    year: 2021,
  },
  "anilist:anime:51367": {
    title: "JoJo's Bizarre Adventure: Stone Ocean Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1051/121959l.webp",
    year: 2022,
  },
  "anilist:anime:53273": {
    title: "JoJo's Bizarre Adventure: Stone Ocean Part 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1233/128920l.webp",
    year: 2022,
  },
  "anilist:anime:30831": {
    title: "KonoSuba: God's Blessing on This Wonderful World!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1895/142748l.webp",
    year: 2016,
  },
  "anilist:anime:32937": {
    title: "KonoSuba: God's Blessing on This Wonderful World! 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/2/83188l.webp",
    year: 2017,
  },
  "anilist:anime:38040": {
    title: "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1638/119321l.webp",
    year: 2019,
  },
  "anilist:anime:49458": {
    title: "KonoSuba: God's Blessing on This Wonderful World! 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1758/141268l.webp",
    year: 2024,
  },
  "anilist:anime:29803": {
    title: "Overlord",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1945/136600l.webp",
    year: 2015,
  },
  "anilist:anime:35073": {
    title: "Overlord II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1212/113415l.webp",
    year: 2018,
  },
  "anilist:anime:37675": {
    title: "Overlord III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1511/93473l.webp",
    year: 2018,
  },
  "anilist:anime:34161": {
    title: "Overlord: The Undead King",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/87759l.webp",
    year: 2017,
  },
  "anilist:anime:34428": {
    title: "Overlord: The Dark Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/87758l.webp",
    year: 2017,
  },
  "anilist:anime:48895": {
    title: "Overlord IV",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1530/120110l.webp",
    year: 2022,
  },
  "anilist:anime:35790": {
    title: "The Rising of the Shield Hero",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1490/101365l.webp",
    year: 2019,
  },
  "anilist:anime:40356": {
    title: "The Rising of the Shield Hero Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1143/121873l.webp",
    year: 2022,
  },
  "anilist:anime:40357": {
    title: "The Rising of the Shield Hero Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1317/139802l.webp",
    year: 2023,
  },
  "anilist:anime:37430": {
    title: "That Time I Got Reincarnated as a Slime",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1069/123309l.webp",
    year: 2018,
  },
  "anilist:anime:39551": {
    title: "That Time I Got Reincarnated as a Slime Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1271/109841l.webp",
    year: 2021,
  },
  "anilist:anime:41487": {
    title: "That Time I Got Reincarnated as a Slime Season 2 Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1033/118296l.webp",
    year: 2021,
  },
  "anilist:anime:49877": {
    title: "That Time I Got Reincarnated as a Slime: The Movie - Scarlet Bond",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1745/128238l.webp",
    year: 2022,
  },
  "anilist:anime:53580": {
    title: "That Time I Got Reincarnated as a Slime Season 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1211/143476l.webp",
    year: 2024,
  },
  "anilist:anime:34599": {
    title: "Made in Abyss",
    posterUrl: "https://cdn.myanimelist.net/images/anime/6/86733l.webp",
    year: 2017,
  },
  "anilist:anime:36862": {
    title: "Made in Abyss: Dawn of the Deep Soul",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1803/117183l.webp",
    year: 2020,
  },
  "anilist:anime:41084": {
    title: "Made in Abyss: The Golden City of the Scorching Sun",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1864/122519l.webp",
    year: 2022,
  },
  "anilist:anime:33352": {
    title: "Violet Evergarden",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1795/95088l.webp",
    year: 2018,
  },
  "anilist:anime:39741": {
    title: "Violet Evergarden: Eternity and the Auto Memory Doll",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1667/112943l.webp",
    year: 2019,
  },
  "anilist:anime:37987": {
    title: "Violet Evergarden: The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1825/110716l.webp",
    year: 2020,
  },
  "anilist:anime:5680": {
    title: "K-ON!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/76120l.webp",
    year: 2009,
  },
  "anilist:anime:7791": {
    title: "K-ON! Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/76121l.webp",
    year: 2010,
  },
  "anilist:anime:9617": {
    title: "K-ON! The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/5/76233l.webp",
    year: 2011,
  },
  "anilist:anime:13601": {
    title: "Psycho-Pass",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1314/142015l.webp",
    year: 2012,
  },
  "anilist:anime:23281": {
    title: "Psycho-Pass 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1197/100616l.webp",
    year: 2014,
  },
  "anilist:anime:21339": {
    title: "Psycho-Pass: The Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/71793l.webp",
    year: 2015,
  },
  "anilist:anime:52747": {
    title: "Psycho-Pass: Providence",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1244/134653l.webp",
    year: 2023,
  },
  "anilist:anime:39491": {
    title: "Psycho-Pass 3",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1406/104344l.webp",
    year: 2019,
  },
  "anilist:anime:40858": {
    title: "Psycho-Pass 3: First Inspector",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1085/110722l.webp",
    year: 2020,
  },
  "anilist:anime:22319": {
    title: "Tokyo Ghoul",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1498/134443l.webp",
    year: 2014,
  },
  "anilist:anime:27899": {
    title: "Tokyo Ghoul √A",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1889/123307l.webp",
    year: 2015,
  },
  "anilist:anime:36511": {
    title: "Tokyo Ghoul:re",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1063/95086l.webp",
    year: 2018,
  },
  "anilist:anime:37799": {
    title: "Tokyo Ghoul:re 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1545/121995l.webp",
    year: 2018,
  },
  "anilist:anime:44511": {
    title: "Chainsaw Man",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1806/126216l.webp",
    year: 2022,
  },
  "anilist:anime:57555": {
    title: "Chainsaw Man – The Movie: Reze Arc",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1763/150638l.webp",
    year: 2025,
  },
  "anilist:anime:50265": {
    title: "Spy x Family",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1441/122795l.webp",
    year: 2022,
  },
  "anilist:anime:50602": {
    title: "Spy x Family Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1111/127508l.webp",
    year: 2022,
  },
  "anilist:anime:53887": {
    title: "Spy x Family Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1506/138982l.webp",
    year: 2023,
  },
  "anilist:anime:53888": {
    title: "Spy x Family Code: White",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1426/139388l.webp",
    year: 2023,
  },
  "anilist:anime:37521": {
    title: "Vinland Saga",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1500/103005l.webp",
    year: 2019,
  },
  "anilist:anime:49387": {
    title: "Vinland Saga Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1170/124312l.webp",
    year: 2023,
  },
  "anilist:anime:38691": {
    title: "Dr. Stone",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1613/102576l.webp",
    year: 2019,
  },
  "anilist:anime:40852": {
    title: "Dr. Stone: Stone Wars",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1711/110614l.webp",
    year: 2021,
  },
  "anilist:anime:50612": {
    title: "Dr. Stone: Ryusui",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1071/124921l.webp",
    year: 2022,
  },
  "anilist:anime:48549": {
    title: "Dr. Stone: New World",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1316/136268l.webp",
    year: 2023,
  },
  "anilist:anime:55644": {
    title: "Dr. Stone: New World Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1236/138696l.webp",
    year: 2023,
  },
  "anilist:anime:57592": {
    title: "Dr. Stone: Science Future",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1403/146479l.webp",
    year: 2025,
  },
  "anilist:anime:61322": {
    title: "Dr. Stone: Science Future Part 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1785/151710l.webp",
    year: 2025,
  },
  "anilist:anime:37779": {
    title: "The Promised Neverland",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1830/118780l.webp",
    year: 2019,
  },
  "anilist:anime:39617": {
    title: "The Promised Neverland Season 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1815/110626l.webp",
    year: 2021,
  },
  "anilist:anime:47616": {
    title: "The Promised Neverland: Guidepost",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1097/111813l.webp",
    year: 2021,
  },
  "anilist:anime:20583": {
    title: "Haikyu!!",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/76014l.webp",
    year: 2014,
  },
  "anilist:anime:28891": {
    title: "Haikyu!! 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/76662l.webp",
    year: 2015,
  },
  "anilist:anime:32935": {
    title: "Haikyu!! 3rd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/7/81992l.webp",
    year: 2016,
  },
  "anilist:anime:38883": {
    title: "Haikyu!! To the Top",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1813/105367l.webp",
    year: 2020,
  },
  "anilist:anime:40776": {
    title: "Haikyu!! To the Top 2nd-cour",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1453/106768l.webp",
    year: 2020,
  },
  "anilist:anime:52742": {
    title: "Haikyu!! Movie: The Dumpster Battle",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1665/140360l.webp",
    year: 2024,
  },
  "anilist:anime:37999": {
    title: "Kaguya-sama: Love is War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1295/106551l.webp",
    year: 2019,
  },
  "anilist:anime:40591": {
    title: "Kaguya-sama: Love is War?",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1764/106659l.webp",
    year: 2020,
  },
  "anilist:anime:43608": {
    title: "Kaguya-sama: Love is War -Ultra Romantic-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1160/122627l.webp",
    year: 2022,
  },
  "anilist:anime:52198": {
    title: "Kaguya-sama: Love is War -The First Kiss That Never Ends-",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1670/130060l.webp",
    year: 2022,
  },
  "anilist:anime:37450": {
    title: "Rascal Does Not Dream of Bunny Girl Senpai",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1301/93586l.webp",
    year: 2018,
  },
  "anilist:anime:38329": {
    title: "Rascal Does Not Dream of a Dreaming Girl",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1613/102179l.webp",
    year: 2019,
  },
  "anilist:anime:53129": {
    title: "Rascal Does Not Dream of a Sister Venturing Out",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1540/134808l.webp",
    year: 2023,
  },
  "anilist:anime:54870": {
    title: "Rascal Does Not Dream of a Knapsack Kid",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1937/138379l.webp",
    year: 2023,
  },
  "anilist:anime:38680": {
    title: "Fruits Basket 1st Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1447/99827l.webp",
    year: 2019,
  },
  "anilist:anime:40417": {
    title: "Fruits Basket 2nd Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1972/111635l.webp",
    year: 2020,
  },
  "anilist:anime:42938": {
    title: "Fruits Basket: The Final Season",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1085/114792l.webp",
    year: 2021,
  },
  "anilist:anime:49310": {
    title: "Fruits Basket: Prelude",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1034/120096l.webp",
    year: 2022,
  },
  "anilist:anime:23755": {
    title: "The Seven Deadly Sins",
    posterUrl: "https://cdn.myanimelist.net/images/anime/8/65409l.webp",
    year: 2014,
  },
  "anilist:anime:31722": {
    title: "The Seven Deadly Sins: Signs of Holy War",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/79331l.webp",
    year: 2016,
  },
  "anilist:anime:34577": {
    title: "The Seven Deadly Sins: Revival of the Commandments",
    posterUrl: "https://cdn.myanimelist.net/images/anime/11/90089l.webp",
    year: 2018,
  },
  "anilist:anime:35946": {
    title: "The Seven Deadly Sins the Movie: Prisoners of the Sky",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1444/91899l.webp",
    year: 2018,
  },
  "anilist:anime:39701": {
    title: "The Seven Deadly Sins: Imperial Wrath of the Gods",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1546/103418l.webp",
    year: 2019,
  },
  "anilist:anime:41491": {
    title: "The Seven Deadly Sins: Dragon's Judgement",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1011/111551l.webp",
    year: 2021,
  },
  "anilist:anime:46420": {
    title: "The Seven Deadly Sins the Movie 2: Cursed By Light",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1096/113360l.webp",
    year: 2021,
  },
  "anilist:anime:15583": {
    title: "Date A Live",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/44844l.webp",
    year: 2013,
  },
  "anilist:anime:19163": {
    title: "Date A Live II",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1690/141818l.webp",
    year: 2014,
  },
  "anilist:anime:24655": {
    title: "Date A Live Movie: Mayuri Judgement",
    posterUrl: "https://cdn.myanimelist.net/images/anime/9/75466l.webp",
    year: 2015,
  },
  "anilist:anime:36633": {
    title: "Date A Live III",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1055/100468l.webp",
    year: 2019,
  },
  "anilist:anime:41461": {
    title: "Date A Live IV",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1368/121281l.webp",
    year: 2022,
  },
  "anilist:anime:52196": {
    title: "Date A Live V",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1659/141438l.webp",
    year: 2024,
  },
  "anilist:anime:2167": {
    title: "Clannad",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1804/95033l.webp",
    year: 2007,
  },
  "anilist:anime:4181": {
    title: "Clannad: After Story",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1299/110774l.webp",
    year: 2008,
  },
  "anilist:anime:4059": {
    title: "Clannad: Another World, Tomoyo Chapter",
    posterUrl: "https://cdn.myanimelist.net/images/anime/12/19620l.webp",
    year: 2008,
  },
  "anilist:anime:6351": {
    title: "Clannad: After Story - Another World, Kyou Chapter",
    posterUrl: "https://cdn.myanimelist.net/images/anime/10/19621l.webp",
    year: 2009,
  },
  "anilist:anime:1723": {
    title: "Clannad The Motion Picture",
    posterUrl: "https://cdn.myanimelist.net/images/anime/13/75650l.webp",
    year: 2007,
  },
  "anilist:anime:38101": {
    title: "The Quintessential Quintuplets",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1819/97947l.webp",
    year: 2019,
  },
  "anilist:anime:39783": {
    title: "The Quintessential Quintuplets 2",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1775/109514l.webp",
    year: 2021,
  },
  "anilist:anime:48548": {
    title: "The Quintessential Quintuplets Movie",
    posterUrl: "https://cdn.myanimelist.net/images/anime/1037/122516l.webp",
    year: 2022,
  },
  "tmdb:movie:49521": {
    title: "El hombre de acero",
    posterUrl: "https://image.tmdb.org/t/p/w342/5JW44QGgpEWx4aWXM0uVSi2xtrI.jpg",
    year: 2013,
  },
  "tmdb:movie:209112": {
    title: "Batman vs Superman: El amanecer de la justicia",
    posterUrl: "https://image.tmdb.org/t/p/w342/mS3t9puIjLKgoex82cu9d6G0835.jpg",
    year: 2016,
  },
  "tmdb:movie:297761": {
    title: "Escuadrón suicida",
    posterUrl: "https://image.tmdb.org/t/p/w342/9ymhU7NclJr29MpZnBQbJurYbuc.jpg",
    year: 2016,
  },
  "tmdb:movie:297762": {
    title: "Wonder Woman",
    posterUrl: "https://image.tmdb.org/t/p/w342/skVHFykCQrEwQJdrpUHgJbvqo1u.jpg",
    year: 2017,
  },
  "tmdb:movie:141052": {
    title: "Liga de la Justicia",
    posterUrl: "https://image.tmdb.org/t/p/w342/wUWqnavD8iGZ5F4xXhWlrtEzKjV.jpg",
    year: 2017,
  },
  "tmdb:movie:297802": {
    title: "Aquaman",
    posterUrl: "https://image.tmdb.org/t/p/w342/yTzr6Nc4RcTXVw9SsWQNJdcjTz5.jpg",
    year: 2018,
  },
  "tmdb:movie:287947": {
    title: "¡Shazam!",
    posterUrl: "https://image.tmdb.org/t/p/w342/kIFthNFctw1ZYEIMer0dVnOln78.jpg",
    year: 2019,
  },
  "tmdb:movie:495764": {
    title: "Aves de presa (y la fantabulosa emancipación de Harley Quinn)",
    posterUrl: "https://image.tmdb.org/t/p/w342/1wLqXiiiaTSK8Y0n7N85O0jaNJm.jpg",
    year: 2020,
  },
  "tmdb:movie:464052": {
    title: "Wonder Woman 1984",
    posterUrl: "https://image.tmdb.org/t/p/w342/jIIjsExCEv6lsfQGHTXDPk3Q0M5.jpg",
    year: 2020,
  },
  "tmdb:movie:436969": {
    title: "El escuadrón suicida",
    posterUrl: "https://image.tmdb.org/t/p/w342/fPJWlhXA2VXf4MlQ3JenVsz1iba.jpg",
    year: 2021,
  },
  "tmdb:movie:436270": {
    title: "Black Adam",
    posterUrl: "https://image.tmdb.org/t/p/w342/moDLTCdLx38kMhN53KOTw0LdWMh.jpg",
    year: 2022,
  },
  "tmdb:movie:594767": {
    title: "¡Shazam! La furia de los dioses",
    posterUrl: "https://image.tmdb.org/t/p/w342/xCxwaQeoIr4FcjlPgHfzog0x4B8.jpg",
    year: 2023,
  },
  "tmdb:movie:298618": {
    title: "Flash",
    posterUrl: "https://image.tmdb.org/t/p/w342/gNbZNuZ2fBferjJspfmvnskODGc.jpg",
    year: 2023,
  },
  "tmdb:movie:565770": {
    title: "Blue Beetle",
    posterUrl: "https://image.tmdb.org/t/p/w342/tf5Mqgoj1fFIeP7Ktfn8KGrYhup.jpg",
    year: 2023,
  },
  "tmdb:movie:572802": {
    title: "Aquaman y el reino perdido",
    posterUrl: "https://image.tmdb.org/t/p/w342/a0QwtpUNIKjOlNoOVmk7d2LFnQW.jpg",
    year: 2023,
  },
  "tmdb:movie:272": {
    title: "Batman Begins",
    posterUrl: "https://image.tmdb.org/t/p/w342/6yMWU1vWkOBbNRIwOxhetd2aHhO.jpg",
    year: 2005,
  },
  "tmdb:movie:155": {
    title: "El caballero oscuro",
    posterUrl: "https://image.tmdb.org/t/p/w342/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg",
    year: 2008,
  },
  "tmdb:movie:49026": {
    title: "El caballero oscuro: La leyenda renace",
    posterUrl: "https://image.tmdb.org/t/p/w342/rrS7K8tXVFUBliIKWaRuSq65nWr.jpg",
    year: 2012,
  },
  "tmdb:movie:36657": {
    title: "X-Men",
    posterUrl: "https://image.tmdb.org/t/p/w342/aF170xLGytZcC0xeSlSamImgIi4.jpg",
    year: 2000,
  },
  "tmdb:movie:36658": {
    title: "X-Men 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/bnZUa8bCq2uz56Jv6Clpcjtvw0V.jpg",
    year: 2003,
  },
  "tmdb:movie:36668": {
    title: "X-Men: La decisión final",
    posterUrl: "https://image.tmdb.org/t/p/w342/6FnWDI3mKZhfWv7NznKUFlvSdo0.jpg",
    year: 2006,
  },
  "tmdb:movie:2080": {
    title: "X-Men orígenes: Lobezno",
    posterUrl: "https://image.tmdb.org/t/p/w342/k2wFS6LAYDjOdSAtRc1Ey7roB4G.jpg",
    year: 2009,
  },
  "tmdb:movie:49538": {
    title: "X-Men: Primera Generación",
    posterUrl: "https://image.tmdb.org/t/p/w342/6ED3G0lpBXRZtEDJD2xVYsqIwxI.jpg",
    year: 2011,
  },
  "tmdb:movie:76170": {
    title: "Lobezno inmortal",
    posterUrl: "https://image.tmdb.org/t/p/w342/xsdBlh5Rg673dRmIblDZchuicWi.jpg",
    year: 2013,
  },
  "tmdb:movie:127585": {
    title: "X-Men: Días del futuro pasado",
    posterUrl: "https://image.tmdb.org/t/p/w342/ggb9nmS5alJuA0ll0iU5YHiGbb0.jpg",
    year: 2014,
  },
  "tmdb:movie:246655": {
    title: "X-Men: Apocalipsis",
    posterUrl: "https://image.tmdb.org/t/p/w342/iKqONIk0oX8rLvxkBCpnkZMTKE3.jpg",
    year: 2016,
  },
  "tmdb:movie:263115": {
    title: "Logan",
    posterUrl: "https://image.tmdb.org/t/p/w342/d0ktjN9eKww26HhM8or8iUB1I68.jpg",
    year: 2017,
  },
  "tmdb:movie:320288": {
    title: "X-Men: Fénix oscura",
    posterUrl: "https://image.tmdb.org/t/p/w342/rdByKDkfyVuVSrkllzxKYXiZmTd.jpg",
    year: 2019,
  },
  "tmdb:movie:340102": {
    title: "Los nuevos mutantes",
    posterUrl: "https://image.tmdb.org/t/p/w342/cNEIc6SbgsNWkzwfw4EuYLqE9Gt.jpg",
    year: 2020,
  },
  "tmdb:movie:293660": {
    title: "Deadpool",
    posterUrl: "https://image.tmdb.org/t/p/w342/3TUYy0XvhPQBhrXJwRIaOoYFOBO.jpg",
    year: 2016,
  },
  "tmdb:movie:383498": {
    title: "Deadpool 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/84NUrv5kuMUDDlOPqi97KGJMdLm.jpg",
    year: 2018,
  },
  "tmdb:movie:533535": {
    title: "Deadpool y Lobezno",
    posterUrl: "https://image.tmdb.org/t/p/w342/9TFSqghEHrlBMRR63yTx80Orxva.jpg",
    year: 2024,
  },
  "tmdb:movie:557": {
    title: "Spider-Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/bCDaKZLRkrVVtPNyHxUfKvepW1N.jpg",
    year: 2002,
  },
  "tmdb:movie:558": {
    title: "Spider-Man 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/tGYrkVuskQKyRZ9WRS6wPTPBJpm.jpg",
    year: 2004,
  },
  "tmdb:movie:559": {
    title: "Spider-Man 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/lkuQzlShE2uzJcsZYU4zBI4VQZP.jpg",
    year: 2007,
  },
  "tmdb:movie:1930": {
    title: "The Amazing Spider-Man",
    posterUrl: "https://image.tmdb.org/t/p/w342/swjygVNvJ84ztpgfFX9gRr2MPBZ.jpg",
    year: 2012,
  },
  "tmdb:movie:102382": {
    title: "The Amazing Spider-Man 2: El poder de Electro",
    posterUrl: "https://image.tmdb.org/t/p/w342/8W0mMrmaVdSoLz5LnX61gJOXfEb.jpg",
    year: 2014,
  },
  "tmdb:movie:324857": {
    title: "Spider-Man: un nuevo universo",
    posterUrl: "https://image.tmdb.org/t/p/w342/xRMZikjAHNFebD1FLRqgDZeGV4a.jpg",
    year: 2018,
  },
  "tmdb:movie:569094": {
    title: "Spider-Man: Cruzando el Multiverso",
    posterUrl: "https://image.tmdb.org/t/p/w342/37WcNMgNOMxdhT87MFl7tq7FM1.jpg",
    year: 2023,
  },
  "tmdb:movie:335983": {
    title: "Venom",
    posterUrl: "https://image.tmdb.org/t/p/w342/jMBTJQiHAyGlZR05J2sq5coA6ew.jpg",
    year: 2018,
  },
  "tmdb:movie:580489": {
    title: "Venom: habrá matanza",
    posterUrl: "https://image.tmdb.org/t/p/w342/b0j9rHYpRML7dKm5xw9e97HTDJF.jpg",
    year: 2021,
  },
  "tmdb:movie:912649": {
    title: "Venom: El último baile",
    posterUrl: "https://image.tmdb.org/t/p/w342/toZiAd0n0NKhiuHTiGk7kBMmhtG.jpg",
    year: 2024,
  },
  "tmdb:movie:671": {
    title: "Harry Potter y la piedra filosofal",
    posterUrl: "https://image.tmdb.org/t/p/w342/3MKK7vAJLtSkBTABMTjxf6TOCo3.jpg",
    year: 2001,
  },
  "tmdb:movie:672": {
    title: "Harry Potter y la cámara secreta",
    posterUrl: "https://image.tmdb.org/t/p/w342/bhCfAzeMMg7GyLDT11yVM2i1NPh.jpg",
    year: 2002,
  },
  "tmdb:movie:673": {
    title: "Harry Potter y el prisionero de Azkaban",
    posterUrl: "https://image.tmdb.org/t/p/w342/wF9aoo4YZmpKP4bZPSy4Zwwek6G.jpg",
    year: 2004,
  },
  "tmdb:movie:674": {
    title: "Harry Potter y el cáliz de fuego",
    posterUrl: "https://image.tmdb.org/t/p/w342/5hrrncgY7GfRHz6JmnhPlvJUONe.jpg",
    year: 2005,
  },
  "tmdb:movie:675": {
    title: "Harry Potter y la Orden del Fénix",
    posterUrl: "https://image.tmdb.org/t/p/w342/xxXiM2Ij7plbzibKWW9BfDk23aI.jpg",
    year: 2007,
  },
  "tmdb:movie:767": {
    title: "Harry Potter y el misterio del príncipe",
    posterUrl: "https://image.tmdb.org/t/p/w342/tO0UGkNuQoxyXve0mvwtXP49NAO.jpg",
    year: 2009,
  },
  "tmdb:movie:12444": {
    title: "Harry Potter y las Reliquias de la Muerte - Parte 1",
    posterUrl: "https://image.tmdb.org/t/p/w342/w6wsYKdXERaXRdByPsI2O9rn20b.jpg",
    year: 2010,
  },
  "tmdb:movie:12445": {
    title: "Harry Potter y las Reliquias de la Muerte - Parte 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/aM1TuUiPtV8OAZyu61CTdy9Ymtk.jpg",
    year: 2011,
  },
  "tmdb:movie:259316": {
    title: "Animales fantásticos y dónde encontrarlos",
    posterUrl: "https://image.tmdb.org/t/p/w342/wduJFXlHQTIw1TBf6kTO3bHf2VN.jpg",
    year: 2016,
  },
  "tmdb:movie:338952": {
    title: "Animales fantásticos: Los crímenes de Grindelwald",
    posterUrl: "https://image.tmdb.org/t/p/w342/p4BabO5lvfXnIsVIBLDpN2wLORz.jpg",
    year: 2018,
  },
  "tmdb:movie:338953": {
    title: "Animales fantásticos: Los secretos de Dumbledore",
    posterUrl: "https://image.tmdb.org/t/p/w342/yOeuJdwag4bAlnvgrdweRoiuXGC.jpg",
    year: 2022,
  },
  "tmdb:movie:120": {
    title: "El señor de los anillos: La comunidad del anillo",
    posterUrl: "https://image.tmdb.org/t/p/w342/9xtH1RmAzQ0rrMBNUMXstb2s3er.jpg",
    year: 2001,
  },
  "tmdb:movie:121": {
    title: "El señor de los anillos: Las dos torres",
    posterUrl: "https://image.tmdb.org/t/p/w342/up6gIHZlfEQZkHIfQwcOOaGOzOt.jpg",
    year: 2002,
  },
  "tmdb:movie:122": {
    title: "El señor de los anillos: El retorno del rey",
    posterUrl: "https://image.tmdb.org/t/p/w342/mWuFbQrXyLk2kMBKF9TUPtDwuPx.jpg",
    year: 2003,
  },
  "tmdb:movie:49051": {
    title: "El hobbit: Un viaje inesperado",
    posterUrl: "https://image.tmdb.org/t/p/w342/3dJELUqdpGEkXVrMj7V3BiOjrtf.jpg",
    year: 2012,
  },
  "tmdb:movie:57158": {
    title: "El hobbit: La desolación de Smaug",
    posterUrl: "https://image.tmdb.org/t/p/w342/1s8xZDmG5IkDU0m1LeW28YcwTRx.jpg",
    year: 2013,
  },
  "tmdb:movie:122917": {
    title: "El hobbit: La batalla de los cinco ejércitos",
    posterUrl: "https://image.tmdb.org/t/p/w342/6OiNSLcRKJsBLXwb6DEi6IQ0JFk.jpg",
    year: 2014,
  },
  "tmdb:movie:411": {
    title: "Las crónicas de Narnia: El león, la bruja y el armario",
    posterUrl: "https://image.tmdb.org/t/p/w342/2Lv2wKf2YocOcRfzmvQYOUGRhFg.jpg",
    year: 2005,
  },
  "tmdb:movie:2454": {
    title: "Las crónicas de Narnia: El príncipe Caspian",
    posterUrl: "https://image.tmdb.org/t/p/w342/ccXSnN0bMBYc7Pno5chkpy7UYcq.jpg",
    year: 2008,
  },
  "tmdb:movie:10140": {
    title: "Las crónicas de Narnia: La travesía del viajero del alba",
    posterUrl: "https://image.tmdb.org/t/p/w342/i1VNVBUkai81eRQTS16zXllnN52.jpg",
    year: 2010,
  },
  "tmdb:movie:22": {
    title: "Piratas del Caribe: La maldición de la Perla Negra",
    posterUrl: "https://image.tmdb.org/t/p/w342/bVG48kmXuLaZYgPfSCmhs6EYFbX.jpg",
    year: 2003,
  },
  "tmdb:movie:58": {
    title: "Piratas del Caribe: El cofre del hombre muerto",
    posterUrl: "https://image.tmdb.org/t/p/w342/7L7H6sHAt48EfwsqFaa0dw2NJhz.jpg",
    year: 2006,
  },
  "tmdb:movie:285": {
    title: "Piratas del Caribe: En el fin del mundo",
    posterUrl: "https://image.tmdb.org/t/p/w342/xHcUMez2b1QiMGQYCuQTAlqwDEe.jpg",
    year: 2007,
  },
  "tmdb:movie:1865": {
    title: "Piratas del Caribe: En mareas misteriosas",
    posterUrl: "https://image.tmdb.org/t/p/w342/2oOARbiV871kCC27FyKBmYwOM3G.jpg",
    year: 2011,
  },
  "tmdb:movie:166426": {
    title: "Piratas del Caribe: La venganza de Salazar",
    posterUrl: "https://image.tmdb.org/t/p/w342/net3hZOe33XbieLzVkfJsQEdig2.jpg",
    year: 2017,
  },
  "tmdb:movie:85": {
    title: "En busca del arca perdida",
    posterUrl: "https://image.tmdb.org/t/p/w342/tECLVwLCMexSkls33RTCwedRZ6d.jpg",
    year: 1981,
  },
  "tmdb:movie:87": {
    title: "Indiana Jones y el templo maldito",
    posterUrl: "https://image.tmdb.org/t/p/w342/tLEaz41vKyKY7AgCTGgijLGWzbk.jpg",
    year: 1984,
  },
  "tmdb:movie:89": {
    title: "Indiana Jones y la última cruzada",
    posterUrl: "https://image.tmdb.org/t/p/w342/5h45gK147AAJpLLC7Cicr597urz.jpg",
    year: 1989,
  },
  "tmdb:movie:217": {
    title: "Indiana Jones y el reino de la calavera de cristal",
    posterUrl: "https://image.tmdb.org/t/p/w342/caC98g0VyWVztBStLu46rpKlbGw.jpg",
    year: 2008,
  },
  "tmdb:movie:335977": {
    title: "Indiana Jones y el dial del destino",
    posterUrl: "https://image.tmdb.org/t/p/w342/3Sj5ubQ0BLXd6JuECq52Ira8Oor.jpg",
    year: 2023,
  },
  "tmdb:movie:564": {
    title: "La momia",
    posterUrl: "https://image.tmdb.org/t/p/w342/aGRMxB5ve2nSKsq8ww6PyUwhWpP.jpg",
    year: 1999,
  },
  "tmdb:movie:1734": {
    title: "El regreso de la momia",
    posterUrl: "https://image.tmdb.org/t/p/w342/x5CeEQ2iq9A20LbU0K4Q1TMxFDs.jpg",
    year: 2001,
  },
  "tmdb:movie:1735": {
    title: "La momia: La tumba del emperador Dragón",
    posterUrl: "https://image.tmdb.org/t/p/w342/wktniKrRfM6yXI2zEsLz9M3gNWP.jpg",
    year: 2008,
  },
  "tmdb:movie:603": {
    title: "Matrix",
    posterUrl: "https://image.tmdb.org/t/p/w342/8rT9kG2EYkZpJmYCuTJNnPDEube.jpg",
    year: 1999,
  },
  "tmdb:movie:604": {
    title: "Matrix Reloaded",
    posterUrl: "https://image.tmdb.org/t/p/w342/7IZk3Xp3HIpRJGXFYNvzmyRwDlt.jpg",
    year: 2003,
  },
  "tmdb:movie:605": {
    title: "Matrix Revolutions",
    posterUrl: "https://image.tmdb.org/t/p/w342/zi1UMF9jIM2JnQz0u2AyUw8QFZi.jpg",
    year: 2003,
  },
  "tmdb:movie:624860": {
    title: "Matrix Resurrections",
    posterUrl: "https://image.tmdb.org/t/p/w342/dLIwpCTf4QoW01pp85KP9jcfTpu.jpg",
    year: 2021,
  },
  "tmdb:movie:218": {
    title: "Terminator",
    posterUrl: "https://image.tmdb.org/t/p/w342/9KI49SBnwAOzGcMw1onIki7vd2.jpg",
    year: 1984,
  },
  "tmdb:movie:280": {
    title: "Terminator 2: El juicio final",
    posterUrl: "https://image.tmdb.org/t/p/w342/10xtoK2SFv6ADIeWxr3mcrjko72.jpg",
    year: 1991,
  },
  "tmdb:movie:296": {
    title: "Terminator 3: La rebelión de las máquinas",
    posterUrl: "https://image.tmdb.org/t/p/w342/ugVNhnnH3DKUZZ3JtzRkViIh4L9.jpg",
    year: 2003,
  },
  "tmdb:movie:534": {
    title: "Terminator: Salvation",
    posterUrl: "https://image.tmdb.org/t/p/w342/qPORLTWsJrqB27xXCkJRMjMl7fk.jpg",
    year: 2009,
  },
  "tmdb:movie:87101": {
    title: "Terminator Génesis",
    posterUrl: "https://image.tmdb.org/t/p/w342/5N5PnUoywvOduFb4Qw6HD2LkMtu.jpg",
    year: 2015,
  },
  "tmdb:movie:290859": {
    title: "Terminator: Destino oscuro",
    posterUrl: "https://image.tmdb.org/t/p/w342/k7PuHoj2oE7nEHExwliF2FSXFnr.jpg",
    year: 2019,
  },
  "tmdb:movie:348": {
    title: "Alien, el octavo pasajero",
    posterUrl: "https://image.tmdb.org/t/p/w342/pZ9cAe5FxexJjpCaeiETbXzz3Fs.jpg",
    year: 1979,
  },
  "tmdb:movie:679": {
    title: "Aliens: El regreso",
    posterUrl: "https://image.tmdb.org/t/p/w342/3QU9EP8BFLnTh6w9ycDSCvhqbRU.jpg",
    year: 1986,
  },
  "tmdb:movie:8077": {
    title: "Alien³",
    posterUrl: "https://image.tmdb.org/t/p/w342/mj4lGdK8dyivFDKoRXEUmkaUKKf.jpg",
    year: 1992,
  },
  "tmdb:movie:8078": {
    title: "Alien: Resurrección",
    posterUrl: "https://image.tmdb.org/t/p/w342/6MLQ5ehGD3b8E0JZ9K2G4cZeFaI.jpg",
    year: 1997,
  },
  "tmdb:movie:70981": {
    title: "Prometheus",
    posterUrl: "https://image.tmdb.org/t/p/w342/5oYpDom6T7c1YiL2j5IImKklws7.jpg",
    year: 2012,
  },
  "tmdb:movie:126889": {
    title: "Alien: Covenant",
    posterUrl: "https://image.tmdb.org/t/p/w342/245tgZ3mTHWs0NRiPSwPjKobKHf.jpg",
    year: 2017,
  },
  "tmdb:movie:945961": {
    title: "Alien: Romulus",
    posterUrl: "https://image.tmdb.org/t/p/w342/8PYqGSd8MOm5ce8io4qNSAiSExW.jpg",
    year: 2024,
  },
  "tmdb:movie:106": {
    title: "Depredador",
    posterUrl: "https://image.tmdb.org/t/p/w342/spgPmu5bTk8N6KZXrIOBwfd3cNb.jpg",
    year: 1987,
  },
  "tmdb:movie:169": {
    title: "Depredador 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/92Lqy293CqAExYXlqDc456eYCWp.jpg",
    year: 1990,
  },
  "tmdb:movie:34851": {
    title: "Predators",
    posterUrl: "https://image.tmdb.org/t/p/w342/mYH9FtLUtaIgiGKrVqo82TklFIY.jpg",
    year: 2010,
  },
  "tmdb:movie:345940": {
    title: "Megalodón",
    posterUrl: "https://image.tmdb.org/t/p/w342/kBl4wXkKVZep4AVVxju67uh6uVV.jpg",
    year: 2018,
  },
  "tmdb:movie:766507": {
    title: "Predator: La presa",
    posterUrl: "https://image.tmdb.org/t/p/w342/sNAMqQ9T7YnXnvUSufeWzaRgK6Y.jpg",
    year: 2022,
  },
  "tmdb:movie:1376434": {
    title: "Predator: Asesino de asesinos",
    posterUrl: "https://image.tmdb.org/t/p/w342/8upWJ1KTR1bAPqXCHAuVOhfuiAZ.jpg",
    year: 2025,
  },
  "tmdb:movie:1242898": {
    title: "Predator: Badlands",
    posterUrl: "https://image.tmdb.org/t/p/w342/8nCEJ5hFJt0h8FhXafHGhEhT8d7.jpg",
    year: 2025,
  },
  "tmdb:movie:9659": {
    title: "Mad Max: Salvajes de la autopista",
    posterUrl: "https://image.tmdb.org/t/p/w342/vWa1DEwV5RbAOiuAm0WNXD3Aydw.jpg",
    year: 1979,
  },
  "tmdb:movie:8810": {
    title: "Mad Max 2: El guerrero de la carretera",
    posterUrl: "https://image.tmdb.org/t/p/w342/udpVgRB3xz5ZN553apthn4TyT6G.jpg",
    year: 1981,
  },
  "tmdb:movie:9355": {
    title: "Mad Max 3: Más allá de la cúpula del trueno",
    posterUrl: "https://image.tmdb.org/t/p/w342/pgmOX4PQl5xPAdAx18zPPnQjQKs.jpg",
    year: 1985,
  },
  "tmdb:movie:76341": {
    title: "Mad Max: Furia en la carretera",
    posterUrl: "https://image.tmdb.org/t/p/w342/fnY0VRsb31A5RLVCBjuR6EFUlo2.jpg",
    year: 2015,
  },
  "tmdb:movie:786892": {
    title: "Furiosa: De la saga Mad Max",
    posterUrl: "https://image.tmdb.org/t/p/w342/tGHUlykWn9V2IIQ4ZaATIAq9VLB.jpg",
    year: 2024,
  },
  "tmdb:movie:871": {
    title: "El planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/pMLpuzyeXFsttiW0dHzJLH5FXyK.jpg",
    year: 1968,
  },
  "tmdb:movie:1685": {
    title: "Regreso al planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/wNh22vYIfd2Xr6zBoh8ZQGivt1L.jpg",
    year: 1970,
  },
  "tmdb:movie:1687": {
    title: "Huida del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/mCbFub0UiNQi3SBSOjwGNLhEroc.jpg",
    year: 1971,
  },
  "tmdb:movie:1688": {
    title: "La rebelión de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/J80xXgT6Mw8EiiQeHcEdJ4LfxC.jpg",
    year: 1972,
  },
  "tmdb:movie:1705": {
    title: "La conquista del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/9kQ0wmBzoL4EZEF2jTft58AhBuv.jpg",
    year: 1973,
  },
  "tmdb:movie:61791": {
    title: "El origen del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/6TqjIMQV11NkHMuriprN3xNoN6o.jpg",
    year: 2011,
  },
  "tmdb:movie:119450": {
    title: "El amanecer del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/mP5Wr0YkO3EDqc6vkvtdifi7KKI.jpg",
    year: 2014,
  },
  "tmdb:movie:281338": {
    title: "La guerra del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/iAm7IAqfK6VL2h1yh9QbpcctaT.jpg",
    year: 2017,
  },
  "tmdb:movie:653346": {
    title: "El reino del planeta de los simios",
    posterUrl: "https://image.tmdb.org/t/p/w342/kkFn3KM47Qq4Wjhd8GuFfe3LX27.jpg",
    year: 2024,
  },
  "tmdb:movie:438631": {
    title: "Dune",
    posterUrl: "https://image.tmdb.org/t/p/w342/szcew6yyjcDvaL0isaPBk2e3nkF.jpg",
    year: 2021,
  },
  "tmdb:movie:693134": {
    title: "Dune: Parte dos",
    posterUrl: "https://image.tmdb.org/t/p/w342/xCHmhHeO7aOCMlzcNukGH6Q7EiD.jpg",
    year: 2024,
  },
  "tmdb:movie:954": {
    title: "Misión imposible",
    posterUrl: "https://image.tmdb.org/t/p/w342/xCpmxw3UUjv4PGzbIPOHeoKAV0l.jpg",
    year: 1996,
  },
  "tmdb:movie:955": {
    title: "Misión imposible 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/mskE3W88cjMRrnKQye8pjmJu3O1.jpg",
    year: 2000,
  },
  "tmdb:movie:956": {
    title: "Misión imposible 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/w61xBgFOfP8Z6uHKIKn1sl1TI8j.jpg",
    year: 2006,
  },
  "tmdb:movie:56292": {
    title: "Misión imposible: Protocolo fantasma",
    posterUrl: "https://image.tmdb.org/t/p/w342/y0hjsPyieqxcunEcAxb9mrrE09c.jpg",
    year: 2011,
  },
  "tmdb:movie:177677": {
    title: "Misión imposible: Nación secreta",
    posterUrl: "https://image.tmdb.org/t/p/w342/q5twcJdIx9Swtl7CyzfvgQckWVK.jpg",
    year: 2015,
  },
  "tmdb:movie:353081": {
    title: "Misión: Imposible - Fallout",
    posterUrl: "https://image.tmdb.org/t/p/w342/cUlWqDLEYMN3OWlOZ0U18WcIw5F.jpg",
    year: 2018,
  },
  "tmdb:movie:575264": {
    title: "Misión: Imposible - Sentencia mortal parte uno",
    posterUrl: "https://image.tmdb.org/t/p/w342/83sGKvCv2T2CulYbd40Aeduc7n2.jpg",
    year: 2023,
  },
  "tmdb:movie:575265": {
    title: "Misión: Imposible - Sentencia final",
    posterUrl: "https://image.tmdb.org/t/p/w342/mKK7cVNg4mQmKl0Qry9fvr5AqP7.jpg",
    year: 2025,
  },
  "tmdb:movie:245891": {
    title: "John Wick (Otro día para matar)",
    posterUrl: "https://image.tmdb.org/t/p/w342/tDl5ac1VJwMRvlgINDCsDCqg9CE.jpg",
    year: 2014,
  },
  "tmdb:movie:324552": {
    title: "John Wick: Pacto de sangre",
    posterUrl: "https://image.tmdb.org/t/p/w342/tAAikrL3kH3TopsDC2Bgo4ARUiP.jpg",
    year: 2017,
  },
  "tmdb:movie:458156": {
    title: "John Wick: Capítulo 3 - Parabellum",
    posterUrl: "https://image.tmdb.org/t/p/w342/aKw7oqYdfn4pkKYvp18Gd1YhK6m.jpg",
    year: 2019,
  },
  "tmdb:movie:603692": {
    title: "John Wick 4",
    posterUrl: "https://image.tmdb.org/t/p/w342/mj2Z9HnRSIEk3n7yVPoOY4Uzzfh.jpg",
    year: 2023,
  },
  "tmdb:movie:9799": {
    title: "A todo gas",
    posterUrl: "https://image.tmdb.org/t/p/w342/mrdf1KTSZxsPzqrrHSSCUV3CoU8.jpg",
    year: 2001,
  },
  "tmdb:movie:584": {
    title: "2 Fast 2 Furious: A todo gas 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/fZtSG5a6i5Ca39WQylLVmvWI5b.jpg",
    year: 2003,
  },
  "tmdb:movie:9615": {
    title: "A todo gas: Tokyo Race",
    posterUrl: "https://image.tmdb.org/t/p/w342/9FBbiTAfBkTLYbqVux9ycqed5vz.jpg",
    year: 2006,
  },
  "tmdb:movie:13804": {
    title: "Fast & Furious: Aún más rápido",
    posterUrl: "https://image.tmdb.org/t/p/w342/5Pf9sP5jmiwUToa1XAdTQQW4CjX.jpg",
    year: 2009,
  },
  "tmdb:movie:51497": {
    title: "Fast & Furious 5",
    posterUrl: "https://image.tmdb.org/t/p/w342/d7OwxVxXdkfUOwh5VvW6JpY0Ot9.jpg",
    year: 2011,
  },
  "tmdb:movie:82992": {
    title: "Fast & Furious 6",
    posterUrl: "https://image.tmdb.org/t/p/w342/6zUkjB5OtiFhN2DiqdT1IllNJTa.jpg",
    year: 2013,
  },
  "tmdb:movie:168259": {
    title: "Fast & Furious 7",
    posterUrl: "https://image.tmdb.org/t/p/w342/yWG5W4tKCQweHEdnKV4YEvqOBGx.jpg",
    year: 2015,
  },
  "tmdb:movie:337339": {
    title: "Fast & Furious 8",
    posterUrl: "https://image.tmdb.org/t/p/w342/vXntMTWnh3QRmbY8z53eUlQKmQB.jpg",
    year: 2017,
  },
  "tmdb:movie:385128": {
    title: "Fast & Furious 9",
    posterUrl: "https://image.tmdb.org/t/p/w342/TX1T3c3CDBN0y8iDNvlQbtiA5Z.jpg",
    year: 2021,
  },
  "tmdb:movie:385687": {
    title: "Fast & Furious X",
    posterUrl: "https://image.tmdb.org/t/p/w342/3P9QvWVN02Etn4kYGC702WVoXEb.jpg",
    year: 2023,
  },
  "tmdb:movie:2501": {
    title: "The Bourne Identity: El caso Bourne",
    posterUrl: "https://image.tmdb.org/t/p/w342/yYH7sqMQ1NJNd6scW44D1WjBmAw.jpg",
    year: 2002,
  },
  "tmdb:movie:2502": {
    title: "El mito de Bourne",
    posterUrl: "https://image.tmdb.org/t/p/w342/kTFFwQHdaTUb5MJmB8KBGO7lh7N.jpg",
    year: 2004,
  },
  "tmdb:movie:2503": {
    title: "El ultimátum de Bourne",
    posterUrl: "https://image.tmdb.org/t/p/w342/ifuhCKw2DZ3ROlz7oSFxtJnznR7.jpg",
    year: 2007,
  },
  "tmdb:movie:49040": {
    title: "El legado de Bourne",
    posterUrl: "https://image.tmdb.org/t/p/w342/pWVaLBdcVrTqSTBKIJLinmuxRso.jpg",
    year: 2012,
  },
  "tmdb:movie:324668": {
    title: "Jason Bourne",
    posterUrl: "https://image.tmdb.org/t/p/w342/jv58uIvzudh2MiBW7VERz9552me.jpg",
    year: 2016,
  },
  "tmdb:movie:36557": {
    title: "Casino Royale",
    posterUrl: "https://image.tmdb.org/t/p/w342/2Tygvjqrd6EfvOLwuS7bEIbHwH9.jpg",
    year: 2006,
  },
  "tmdb:movie:10764": {
    title: "Quantum of Solace",
    posterUrl: "https://image.tmdb.org/t/p/w342/zXkvsMkHbvFT9FMw7U9df0ZDuhb.jpg",
    year: 2008,
  },
  "tmdb:movie:37724": {
    title: "Skyfall",
    posterUrl: "https://image.tmdb.org/t/p/w342/lz5kTkm3az7Ww0uTLRvCGgudnaa.jpg",
    year: 2012,
  },
  "tmdb:movie:206647": {
    title: "Spectre",
    posterUrl: "https://image.tmdb.org/t/p/w342/8NCrCV6tR0Uafp8eVYiZbRsvrAv.jpg",
    year: 2015,
  },
  "tmdb:movie:370172": {
    title: "Sin tiempo para morir",
    posterUrl: "https://image.tmdb.org/t/p/w342/4yk2270JA6QpnN8xkuRsnPVXgdP.jpg",
    year: 2021,
  },
  "tmdb:movie:476669": {
    title: "The King's Man: La primera misión",
    posterUrl: "https://image.tmdb.org/t/p/w342/3vBuTxmO4fqbZiZe8i9cqmfiUh6.jpg",
    year: 2021,
  },
  "tmdb:movie:207703": {
    title: "Kingsman: Servicio secreto",
    posterUrl: "https://image.tmdb.org/t/p/w342/2RNABhJ8sTfenTz84ADVUbPllxq.jpg",
    year: 2015,
  },
  "tmdb:movie:343668": {
    title: "Kingsman: El círculo de oro",
    posterUrl: "https://image.tmdb.org/t/p/w342/d0tCSswCeMBzaDsyXc82qfDDvPD.jpg",
    year: 2017,
  },
  "tmdb:movie:8681": {
    title: "Venganza",
    posterUrl: "https://image.tmdb.org/t/p/w342/fO9HTzeL7sd346tybTfbd99Nv3R.jpg",
    year: 2008,
  },
  "tmdb:movie:82675": {
    title: "Venganza: Conexión Estambul",
    posterUrl: "https://image.tmdb.org/t/p/w342/2RQkFjXnqLxc6F8H4VsitxvSyuk.jpg",
    year: 2012,
  },
  "tmdb:movie:260346": {
    title: "V3nganza",
    posterUrl: "https://image.tmdb.org/t/p/w342/hCffcXqpH002rvSFt8AUnIC376s.jpg",
    year: 2014,
  },
  "tmdb:movie:862": {
    title: "Toy Story",
    posterUrl: "https://image.tmdb.org/t/p/w342/y59d8PjuFSgJJN4VRS7jDoRgSM9.jpg",
    year: 1995,
  },
  "tmdb:movie:863": {
    title: "Toy Story 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/6zI0N9blJ9DwuV2xgl3TdGFLtn0.jpg",
    year: 1999,
  },
  "tmdb:movie:10193": {
    title: "Toy Story 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/yBSISwqix2z0JiwIrM3r6fiI6Cm.jpg",
    year: 2010,
  },
  "tmdb:movie:301528": {
    title: "Toy Story 4",
    posterUrl: "https://image.tmdb.org/t/p/w342/yF1vPDuHVrAUMX5dy1tVMbAjkEL.jpg",
    year: 2019,
  },
  "tmdb:movie:808": {
    title: "Shrek",
    posterUrl: "https://image.tmdb.org/t/p/w342/jTQONM7jt1yv2lL972TtmWO0UIZ.jpg",
    year: 2001,
  },
  "tmdb:movie:809": {
    title: "Shrek 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/knRt4E8KyfwEv0SVu9LsLvD28IQ.jpg",
    year: 2004,
  },
  "tmdb:movie:810": {
    title: "Shrek tercero",
    posterUrl: "https://image.tmdb.org/t/p/w342/7sTwtmVPTX77CFOUXdwAM7lKtKL.jpg",
    year: 2007,
  },
  "tmdb:movie:10192": {
    title: "Shrek, Felices para siempre",
    posterUrl: "https://image.tmdb.org/t/p/w342/11K03KebrdD8nUlGFJX3rSL3KHK.jpg",
    year: 2010,
  },
  "tmdb:movie:10191": {
    title: "Cómo entrenar a tu dragón",
    posterUrl: "https://image.tmdb.org/t/p/w342/8ekxsUORMAsfmSc8GzHmG8gWPbp.jpg",
    year: 2010,
  },
  "tmdb:movie:82702": {
    title: "Cómo entrenar a tu dragón 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/bXcRw7FL8QzUZOvY2fZdwDv5ymQ.jpg",
    year: 2014,
  },
  "tmdb:movie:166428": {
    title: "Cómo entrenar a tu dragón 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/rhnoAReqO3Xoe6GbJhT3409lnq8.jpg",
    year: 2019,
  },
  "tmdb:movie:9502": {
    title: "Kung Fu Panda",
    posterUrl: "https://image.tmdb.org/t/p/w342/zcORJ8s9zsBjvKxP0k4FASQSjpf.jpg",
    year: 2008,
  },
  "tmdb:movie:49444": {
    title: "Kung Fu Panda 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/aNji9U9SPTecmoqGippQUBEyouy.jpg",
    year: 2011,
  },
  "tmdb:movie:140300": {
    title: "Kung Fu Panda 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/t11f8palNbICK9Ip5QLrUfhLJYq.jpg",
    year: 2016,
  },
  "tmdb:movie:1011985": {
    title: "Kung Fu Panda 4",
    posterUrl: "https://image.tmdb.org/t/p/w342/2xgGWjM3a38E4KTLapvC53RnpN1.jpg",
    year: 2024,
  },
  "tmdb:movie:953": {
    title: "Madagascar",
    posterUrl: "https://image.tmdb.org/t/p/w342/zrV5GnfCcLWzyjrFgYTpjQPRMfl.jpg",
    year: 2005,
  },
  "tmdb:movie:10527": {
    title: "Madagascar 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/zYbvSjajQrb2jU9rUo5Mt06stPd.jpg",
    year: 2008,
  },
  "tmdb:movie:80321": {
    title: "Madagascar 3: De marcha por Europa",
    posterUrl: "https://image.tmdb.org/t/p/w342/8fKTIecTVNURB6CRFjYMypggRL2.jpg",
    year: 2012,
  },
  "tmdb:movie:20352": {
    title: "Gru Mi villano favorito",
    posterUrl: "https://image.tmdb.org/t/p/w342/AsaaPLSfisdFDeasEd9r0GiZVss.jpg",
    year: 2010,
  },
  "tmdb:movie:93456": {
    title: "Gru 2. Mi villano favorito",
    posterUrl: "https://image.tmdb.org/t/p/w342/hhksXOBVJ6Mu2BwAFgPJwZxNisd.jpg",
    year: 2013,
  },
  "tmdb:movie:211672": {
    title: "Los Minions",
    posterUrl: "https://image.tmdb.org/t/p/w342/nmqLwaTfgyWLQWbYd82w159cAqJ.jpg",
    year: 2015,
  },
  "tmdb:movie:324852": {
    title: "Gru 3. Mi villano favorito",
    posterUrl: "https://image.tmdb.org/t/p/w342/mz3zTmsnySgFWGc3ZsBbCQbalut.jpg",
    year: 2017,
  },
  "tmdb:movie:438148": {
    title: "Minions: El origen de Gru",
    posterUrl: "https://image.tmdb.org/t/p/w342/fzwG3cukayxKpCK0lqS1jkSBqJk.jpg",
    year: 2022,
  },
  "tmdb:movie:519182": {
    title: "Gru 4. Mi villano favorito",
    posterUrl: "https://image.tmdb.org/t/p/w342/b6JX0fBne5yPFNBtdp4Imi3CpiE.jpg",
    year: 2024,
  },
  "tmdb:movie:425": {
    title: "Ice Age: La edad de hielo",
    posterUrl: "https://image.tmdb.org/t/p/w342/9rpdhn7p7mDZW2rUXsINf9c6sR5.jpg",
    year: 2002,
  },
  "tmdb:movie:950": {
    title: "Ice Age 2: El deshielo",
    posterUrl: "https://image.tmdb.org/t/p/w342/q3D7vBGrJVrVrZSJjVQN8lN0e6c.jpg",
    year: 2006,
  },
  "tmdb:movie:8355": {
    title: "Ice Age 3: El origen de los dinosaurios",
    posterUrl: "https://image.tmdb.org/t/p/w342/zufHIdp8szvgkt8VCnJEF2fo1tN.jpg",
    year: 2009,
  },
  "tmdb:movie:57800": {
    title: "Ice Age 4: La formación de los continentes",
    posterUrl: "https://image.tmdb.org/t/p/w342/qYiZOCXkOYtYfolUUdJKoZ8xPsL.jpg",
    year: 2012,
  },
  "tmdb:movie:278154": {
    title: "Ice Age: El gran cataclismo",
    posterUrl: "https://image.tmdb.org/t/p/w342/vgxlqI40AUXmpBzcwlLsYZI5EcR.jpg",
    year: 2016,
  },
  "tmdb:movie:920": {
    title: "Cars",
    posterUrl: "https://image.tmdb.org/t/p/w342/lgBe9KD6DoLyQP28JZ6fSUGK8j0.jpg",
    year: 2006,
  },
  "tmdb:movie:49013": {
    title: "Cars 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/eQo1LQs5Vo9RHVHYUhNSfMZa3VB.jpg",
    year: 2011,
  },
  "tmdb:movie:260514": {
    title: "Cars 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/4tp9W3QAbQcpanBtBceZtHD10UT.jpg",
    year: 2017,
  },
  "tmdb:movie:138843": {
    title: "Expediente Warren: The Conjuring",
    posterUrl: "https://image.tmdb.org/t/p/w342/sKuHxkCogdk6YWzTyXYPoo9qd9n.jpg",
    year: 2013,
  },
  "tmdb:movie:250546": {
    title: "Annabelle",
    posterUrl: "https://image.tmdb.org/t/p/w342/sFxgTJizaUUI3NByNT80oCVnkA2.jpg",
    year: 2014,
  },
  "tmdb:movie:259693": {
    title: "Expediente Warren: El caso Enfield",
    posterUrl: "https://image.tmdb.org/t/p/w342/pdNW0HWw11Wn2N94VGea8O44wOA.jpg",
    year: 2016,
  },
  "tmdb:movie:396422": {
    title: "Annabelle: Creation",
    posterUrl: "https://image.tmdb.org/t/p/w342/dpdPo1kPE5y1pBopxKnchlSX8i8.jpg",
    year: 2017,
  },
  "tmdb:movie:439079": {
    title: "La monja",
    posterUrl: "https://image.tmdb.org/t/p/w342/7fxjwtEvqI1BYkXEbGqJ3dQBgXD.jpg",
    year: 2018,
  },
  "tmdb:movie:480414": {
    title: "La Llorona",
    posterUrl: "https://image.tmdb.org/t/p/w342/1BIWytsnEr2aRobU6ERutzewm63.jpg",
    year: 2019,
  },
  "tmdb:movie:521029": {
    title: "Annabelle: Vuelve a casa",
    posterUrl: "https://image.tmdb.org/t/p/w342/zxwPksbRKGaAi06rapPfFTVsMHv.jpg",
    year: 2019,
  },
  "tmdb:movie:423108": {
    title: "Expediente Warren: Obligado por el demonio",
    posterUrl: "https://image.tmdb.org/t/p/w342/ghMQALCyytc6W0wlOlMIKiMSRKV.jpg",
    year: 2021,
  },
  "tmdb:movie:968051": {
    title: "La monja II",
    posterUrl: "https://image.tmdb.org/t/p/w342/cRp5MhCXwyEjJ3gqynmUME4nJPv.jpg",
    year: 2023,
  },
  "tmdb:movie:1038392": {
    title: "Expediente Warren: El último rito",
    posterUrl: "https://image.tmdb.org/t/p/w342/qdoqogLNR6myoRrxYFxF4UTkFne.jpg",
    year: 2025,
  },
  "tmdb:movie:4232": {
    title: "Scream",
    posterUrl: "https://image.tmdb.org/t/p/w342/pO39MWOrEmJYthKyWT79BYCVRrO.jpg",
    year: 1996,
  },
  "tmdb:movie:4233": {
    title: "Scream 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/iCWp5oRMf7uGWqOCVfLOA5xLorZ.jpg",
    year: 1997,
  },
  "tmdb:movie:4234": {
    title: "Scream 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/dEEvUjBFW1JOVoDnJ7LxZRw75Ik.jpg",
    year: 2000,
  },
  "tmdb:movie:41446": {
    title: "Scream 4",
    posterUrl: "https://image.tmdb.org/t/p/w342/sr7WNBgjX1UH9yw4Qq4o6GLAyVf.jpg",
    year: 2011,
  },
  "tmdb:movie:646385": {
    title: "Scream",
    posterUrl: "https://image.tmdb.org/t/p/w342/85euDQpOU7YNMVMdPZY1KuMe3q5.jpg",
    year: 2022,
  },
  "tmdb:movie:934433": {
    title: "Scream VI",
    posterUrl: "https://image.tmdb.org/t/p/w342/zh0JffFtxcWEJBLKayH3d34WnNT.jpg",
    year: 2023,
  },
  "tmdb:movie:176": {
    title: "Saw",
    posterUrl: "https://image.tmdb.org/t/p/w342/k9h1Don5JWNhLMAjspwbiMMoDzS.jpg",
    year: 2004,
  },
  "tmdb:movie:215": {
    title: "Saw II",
    posterUrl: "https://image.tmdb.org/t/p/w342/gw7nQp0rXmEF81SvumCXWx7U5nb.jpg",
    year: 2005,
  },
  "tmdb:movie:214": {
    title: "Saw III",
    posterUrl: "https://image.tmdb.org/t/p/w342/raUejCvrhUl0VTjcj8b0gJLBUhQ.jpg",
    year: 2006,
  },
  "tmdb:movie:663": {
    title: "Saw IV",
    posterUrl: "https://image.tmdb.org/t/p/w342/owzhppFoegtjAkEhyxQhRtgPl96.jpg",
    year: 2007,
  },
  "tmdb:movie:11917": {
    title: "Saw V",
    posterUrl: "https://image.tmdb.org/t/p/w342/1kxceLYLH3QB8QgtJeTDAQm1fjP.jpg",
    year: 2008,
  },
  "tmdb:movie:22804": {
    title: "Saw VI",
    posterUrl: "https://image.tmdb.org/t/p/w342/xeRsqKxQyMemmBZ4BSkzhwVPeud.jpg",
    year: 2009,
  },
  "tmdb:movie:41439": {
    title: "Saw VII",
    posterUrl: "https://image.tmdb.org/t/p/w342/gn4z3QWHyBVbIIRNucsW6xuhJE2.jpg",
    year: 2010,
  },
  "tmdb:movie:298250": {
    title: "Saw VIII",
    posterUrl: "https://image.tmdb.org/t/p/w342/90T0Cjx2yl6RaFhxas1eKnCphh5.jpg",
    year: 2017,
  },
  "tmdb:movie:602734": {
    title: "Spiral: Saw",
    posterUrl: "https://image.tmdb.org/t/p/w342/97WyFdS8pQerysSSGezafXHW5ZH.jpg",
    year: 2021,
  },
  "tmdb:movie:951491": {
    title: "Saw X",
    posterUrl: "https://image.tmdb.org/t/p/w342/nzVkXj1IX0BNoYzpTVogtkcCStf.jpg",
    year: 2023,
  },
  "tmdb:movie:948": {
    title: "La noche de Halloween",
    posterUrl: "https://image.tmdb.org/t/p/w342/6bsDpDL312h6vEGPOPWoweaZWUG.jpg",
    year: 1978,
  },
  "tmdb:movie:11281": {
    title: "Halloween II: Sanguinario",
    posterUrl: "https://image.tmdb.org/t/p/w342/apMPhXFMkqfBHx8ltZKMDB9JuAi.jpg",
    year: 1981,
  },
  "tmdb:movie:10676": {
    title: "Halloween III: El día de la bruja",
    posterUrl: "https://image.tmdb.org/t/p/w342/hbnLPuazrrUqHxbm2Tsd22tHdHQ.jpg",
    year: 1982,
  },
  "tmdb:movie:11357": {
    title: "Halloween 4: El regreso de Michael Myers",
    posterUrl: "https://image.tmdb.org/t/p/w342/dajbRAwMb2hLGrTQwOHeCc6ouPR.jpg",
    year: 1988,
  },
  "tmdb:movie:11361": {
    title: "Halloween 5: La venganza de Michael Myers",
    posterUrl: "https://image.tmdb.org/t/p/w342/aYW5YLdTQQ8taHCo8ezblLATCOB.jpg",
    year: 1989,
  },
  "tmdb:movie:10987": {
    title: "Halloween 6: La maldición de Michael Myers",
    posterUrl: "https://image.tmdb.org/t/p/w342/gZTdirlRJUAJz36ex46VF1kUrpJ.jpg",
    year: 1995,
  },
  "tmdb:movie:11675": {
    title: "Halloween: H20. Veinte años después",
    posterUrl: "https://image.tmdb.org/t/p/w342/2xj2z8qqs6r5FTSe4tAuqCrYjK5.jpg",
    year: 1998,
  },
  "tmdb:movie:11442": {
    title: "Halloween: Resurrection",
    posterUrl: "https://image.tmdb.org/t/p/w342/oY7zaqkuiO7uVvKzl1yL7iIHauR.jpg",
    year: 2002,
  },
  "tmdb:movie:424139": {
    title: "La noche de Halloween",
    posterUrl: "https://image.tmdb.org/t/p/w342/tRwuTL3KhU03MA2EkXNdRXhH49V.jpg",
    year: 2018,
  },
  "tmdb:movie:610253": {
    title: "Halloween Kills",
    posterUrl: "https://image.tmdb.org/t/p/w342/j1Jf5OCpjCDBCp4K7Nnh8JlvNUJ.jpg",
    year: 2021,
  },
  "tmdb:movie:616820": {
    title: "Halloween: El final",
    posterUrl: "https://image.tmdb.org/t/p/w342/nP53tROjP7v9YnVF3lsFkOZRjF8.jpg",
    year: 2022,
  },
  "tmdb:movie:49018": {
    title: "Insidious",
    posterUrl: "https://image.tmdb.org/t/p/w342/gIrBcrmtL2KEiydYKk8r94o1UGI.jpg",
    year: 2011,
  },
  "tmdb:movie:91586": {
    title: "Insidious: Capítulo 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/ybzJLYR0AbtFphcj6kMqe08Ak1F.jpg",
    year: 2013,
  },
  "tmdb:movie:280092": {
    title: "Insidious: Capítulo 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/yc8vkZgbaJjaZjEE1K1qMrDWiB5.jpg",
    year: 2015,
  },
  "tmdb:movie:406563": {
    title: "Insidious: La última llave",
    posterUrl: "https://image.tmdb.org/t/p/w342/d5l0baYosvDH4HCEc6O7h1QgAp9.jpg",
    year: 2018,
  },
  "tmdb:movie:614479": {
    title: "Insidious: La puerta roja",
    posterUrl: "https://image.tmdb.org/t/p/w342/wD4eLIHUaTvrXQqAzlfduHQ1NYg.jpg",
    year: 2023,
  },
  "tmdb:movie:346364": {
    title: "It (Eso)",
    posterUrl: "https://image.tmdb.org/t/p/w342/sSrj4lnhrb113DOPEPTaO2jaDk3.jpg",
    year: 2017,
  },
  "tmdb:movie:474350": {
    title: "It: Capítulo 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/9oERKIVyTWpHNum3STVsAGD4ojz.jpg",
    year: 2019,
  },
  "tmdb:movie:447332": {
    title: "Un lugar tranquilo",
    posterUrl: "https://image.tmdb.org/t/p/w342/5pairI20KJs1SEa4Z8yAsPR779m.jpg",
    year: 2018,
  },
  "tmdb:movie:520763": {
    title: "Un lugar tranquilo 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/6uRb5axnwAd17h4ak4ENHcJqHVr.jpg",
    year: 2021,
  },
  "tmdb:movie:762441": {
    title: "Un lugar tranquilo: Día uno",
    posterUrl: "https://image.tmdb.org/t/p/w342/6efQJ7pu9GPketUDBAhJtgZLkvD.jpg",
    year: 2024,
  },
  "tmdb:movie:23827": {
    title: "Paranormal Activity",
    posterUrl: "https://image.tmdb.org/t/p/w342/919Xf5NshBIKuj4HP2XkGIfNaCF.jpg",
    year: 2007,
  },
  "tmdb:movie:41436": {
    title: "Paranormal Activity 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/b4Vuhm8L50nhVRUDqT5hbP4aG3x.jpg",
    year: 2010,
  },
  "tmdb:movie:72571": {
    title: "Paranormal Activity 3",
    posterUrl: "https://image.tmdb.org/t/p/w342/2mgtnguCilTT7OtSURCWWE65iWr.jpg",
    year: 2011,
  },
  "tmdb:movie:82990": {
    title: "Paranormal Activity 4",
    posterUrl: "https://image.tmdb.org/t/p/w342/zthZf2pnhmtQGFZhbHEcUlilsL4.jpg",
    year: 2012,
  },
  "tmdb:movie:227348": {
    title: "Paranormal Activity: Los señalados",
    posterUrl: "https://image.tmdb.org/t/p/w342/ykyXkeoUb4RDUge7ZfiiIuVJ1bG.jpg",
    year: 2014,
  },
  "tmdb:movie:146301": {
    title: "Paranormal Activity: Dimensión fantasma",
    posterUrl: "https://image.tmdb.org/t/p/w342/wq7z719J82BvcxYfc4i2CpKvWCU.jpg",
    year: 2015,
  },
  "tmdb:movie:609972": {
    title: "Paranormal Activity: Allegados",
    posterUrl: "https://image.tmdb.org/t/p/w342/5idw994cLDgixK2zuacXrAlYBp3.jpg",
    year: 2021,
  },
  "tmdb:movie:329": {
    title: "Jurassic Park (Parque Jurásico)",
    posterUrl: "https://image.tmdb.org/t/p/w342/h831eszSFmEyr94WKcgscqPIRbh.jpg",
    year: 1993,
  },
  "tmdb:movie:330": {
    title: "El mundo perdido: Jurassic Park",
    posterUrl: "https://image.tmdb.org/t/p/w342/80pXV9DEd81rBGqmlPBLbvr6h9a.jpg",
    year: 1997,
  },
  "tmdb:movie:331": {
    title: "Jurassic Park III (Parque Jurásico III)",
    posterUrl: "https://image.tmdb.org/t/p/w342/5GM4Nqc79PFE3IOqNKwmOxAWkX1.jpg",
    year: 2001,
  },
  "tmdb:movie:135397": {
    title: "Jurassic World",
    posterUrl: "https://image.tmdb.org/t/p/w342/sOgfattHPWE5sWdVCGHQ08GEbaP.jpg",
    year: 2015,
  },
  "tmdb:movie:351286": {
    title: "Jurassic World: El reino caído",
    posterUrl: "https://image.tmdb.org/t/p/w342/yHa2I7qxZvZUASLHrIR8vQLmZ4B.jpg",
    year: 2018,
  },
  "tmdb:movie:507086": {
    title: "Jurassic World: Dominion",
    posterUrl: "https://image.tmdb.org/t/p/w342/sXeWfpT1EhG7f4uBouqraOhmouH.jpg",
    year: 2022,
  },
  "tmdb:movie:1858": {
    title: "Transformers",
    posterUrl: "https://image.tmdb.org/t/p/w342/jNZOozjyWKC0jTTvpZ3KOobGcED.jpg",
    year: 2007,
  },
  "tmdb:movie:8373": {
    title: "Transformers: La venganza de los caídos",
    posterUrl: "https://image.tmdb.org/t/p/w342/qzEIlhHivIcpKhKVOkb61eBz2Mv.jpg",
    year: 2009,
  },
  "tmdb:movie:38356": {
    title: "Transformers: El lado oscuro de la luna",
    posterUrl: "https://image.tmdb.org/t/p/w342/fMqXNNgzTaxalU1ve9KevpELiGe.jpg",
    year: 2011,
  },
  "tmdb:movie:91314": {
    title: "Transformers: La era de la extinción",
    posterUrl: "https://image.tmdb.org/t/p/w342/owqV5Qo2DMMomfB1fS6xYWv3yEh.jpg",
    year: 2014,
  },
  "tmdb:movie:335988": {
    title: "Transformers: El último caballero",
    posterUrl: "https://image.tmdb.org/t/p/w342/mXEBnMqFwTJCrddVhknCH9fq3fB.jpg",
    year: 2017,
  },
  "tmdb:movie:424783": {
    title: "Bumblebee",
    posterUrl: "https://image.tmdb.org/t/p/w342/lOW8vBMJqWHWcMxHbigVAytqiBn.jpg",
    year: 2018,
  },
  "tmdb:movie:667538": {
    title: "Transformers: El despertar de las bestias",
    posterUrl: "https://image.tmdb.org/t/p/w342/peIB7KBBrqW0JsCLQBt9ChEtZ7m.jpg",
    year: 2023,
  },
  "tmdb:movie:1366": {
    title: "Rocky",
    posterUrl: "https://image.tmdb.org/t/p/w342/yyoGappf3WxXRrHz23yNbH2MffI.jpg",
    year: 1976,
  },
  "tmdb:movie:1367": {
    title: "Rocky II",
    posterUrl: "https://image.tmdb.org/t/p/w342/nMaiiu0CzT77U4JZkUYV7KqdAjK.jpg",
    year: 1979,
  },
  "tmdb:movie:1371": {
    title: "Rocky III",
    posterUrl: "https://image.tmdb.org/t/p/w342/5Mn0xgB8w9mi2Ifo7WdS8aSgA7V.jpg",
    year: 1982,
  },
  "tmdb:movie:1374": {
    title: "Rocky IV",
    posterUrl: "https://image.tmdb.org/t/p/w342/2MHUit4H6OK5adcOjnCN6suCKOl.jpg",
    year: 1985,
  },
  "tmdb:movie:1375": {
    title: "Rocky V",
    posterUrl: "https://image.tmdb.org/t/p/w342/kbt9oSpAX8TkmpV2T72p0Cl41vR.jpg",
    year: 1990,
  },
  "tmdb:movie:1246": {
    title: "Rocky Balboa",
    posterUrl: "https://image.tmdb.org/t/p/w342/8oN30JAimKk2LcLOusSYpGvMPgG.jpg",
    year: 2006,
  },
  "tmdb:movie:312221": {
    title: "Creed. La leyenda de Rocky",
    posterUrl: "https://image.tmdb.org/t/p/w342/fTdozSSr2cTZcioldjfVUbBzhrW.jpg",
    year: 2015,
  },
  "tmdb:movie:480530": {
    title: "Creed II: La leyenda de Rocky",
    posterUrl: "https://image.tmdb.org/t/p/w342/2t53WEu1Ck7qAMS3theMnQK2N2c.jpg",
    year: 2018,
  },
  "tmdb:movie:677179": {
    title: "Creed III",
    posterUrl: "https://image.tmdb.org/t/p/w342/fcFMd3HdyX7r5gtFwVnn2qr5Yhq.jpg",
    year: 2023,
  },
  "tmdb:movie:105": {
    title: "Regreso al futuro",
    posterUrl: "https://image.tmdb.org/t/p/w342/owk40tn1sFJmC7bhamEpmhdZPKa.jpg",
    year: 1985,
  },
  "tmdb:movie:165": {
    title: "Regreso al futuro II",
    posterUrl: "https://image.tmdb.org/t/p/w342/oTiQdzBOP5biNvzvrSPAvPxiSKH.jpg",
    year: 1989,
  },
  "tmdb:movie:196": {
    title: "Regreso al futuro III",
    posterUrl: "https://image.tmdb.org/t/p/w342/yamBr3ihlWFF9jh3oOODSvjDY2e.jpg",
    year: 1990,
  },
  "tmdb:movie:238": {
    title: "El padrino",
    posterUrl: "https://image.tmdb.org/t/p/w342/ApiEfzSkrqS4m1L5a2GwWXzIiAs.jpg",
    year: 1972,
  },
  "tmdb:movie:240": {
    title: "El Padrino Parte II",
    posterUrl: "https://image.tmdb.org/t/p/w342/mbry0W5PRylSUHsYzdiY2FSJwze.jpg",
    year: 1974,
  },
  "tmdb:movie:242": {
    title: "El Padrino Parte III",
    posterUrl: "https://image.tmdb.org/t/p/w342/l2D8Gzuzw8hN41UthdqM9Osu9I3.jpg",
    year: 1990,
  },
  "tmdb:movie:70160": {
    title: "Los Juegos del Hambre",
    posterUrl: "https://image.tmdb.org/t/p/w342/qSEn7KsGchT7qB08HlviyeTPrEr.jpg",
    year: 2012,
  },
  "tmdb:movie:101299": {
    title: "Los Juegos del Hambre: En llamas",
    posterUrl: "https://image.tmdb.org/t/p/w342/oxnKI1qiHz7xC0mNthC7dSqTcot.jpg",
    year: 2013,
  },
  "tmdb:movie:131631": {
    title: "Los Juegos del Hambre: Sinsajo - Parte 1",
    posterUrl: "https://image.tmdb.org/t/p/w342/wfLsciidZamFPeOb4FD8ywk1Q9c.jpg",
    year: 2014,
  },
  "tmdb:movie:131634": {
    title: "Los Juegos del Hambre: Sinsajo - Parte 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/3qQPBc7JVGXJGo0Av5jrqndcdTm.jpg",
    year: 2015,
  },
  "tmdb:movie:695721": {
    title: "Los Juegos del Hambre: Balada de pájaros cantores y serpientes",
    posterUrl: "https://image.tmdb.org/t/p/w342/2vIK81ikjvdewSLmrwIg7AMoJIv.jpg",
    year: 2023,
  },
  "tmdb:movie:198663": {
    title: "El corredor del laberinto",
    posterUrl: "https://image.tmdb.org/t/p/w342/egKi4jZKKVZzR8NaaNjEwMpEgHs.jpg",
    year: 2014,
  },
  "tmdb:movie:294254": {
    title: "El corredor del laberinto: Las pruebas",
    posterUrl: "https://image.tmdb.org/t/p/w342/43K7XwlFzO5PGdNMFY5s36jXdWo.jpg",
    year: 2015,
  },
  "tmdb:movie:336843": {
    title: "El corredor del laberinto: La cura mortal",
    posterUrl: "https://image.tmdb.org/t/p/w342/kuZOnvzplxPVh71t827F19zY5Ab.jpg",
    year: 2018,
  },
  "tmdb:movie:8966": {
    title: "Crepúsculo",
    posterUrl: "https://image.tmdb.org/t/p/w342/40ollvfwHaVF85lkkg522SIl3Qc.jpg",
    year: 2008,
  },
  "tmdb:movie:18239": {
    title: "La saga Crepúsculo: Luna nueva",
    posterUrl: "https://image.tmdb.org/t/p/w342/l5lF8VHTO5QKObAKE3Wp2QQfGZJ.jpg",
    year: 2009,
  },
  "tmdb:movie:24021": {
    title: "La saga Crepúsculo: Eclipse",
    posterUrl: "https://image.tmdb.org/t/p/w342/mckJPxNAQ51beBQw82evAa9a2Wd.jpg",
    year: 2010,
  },
  "tmdb:movie:50619": {
    title: "La saga Crepúsculo: Amanecer - Parte 1",
    posterUrl: "https://image.tmdb.org/t/p/w342/27WlKKz9f3vMr6JvSf0LDBVdtaZ.jpg",
    year: 2011,
  },
  "tmdb:movie:50620": {
    title: "La saga Crepúsculo: Amanecer - Parte 2",
    posterUrl: "https://image.tmdb.org/t/p/w342/pPB3rQx0oBOmj5CHZxLWgexo5nS.jpg",
    year: 2012,
  },
  "tmdb:tv:1396": {
    title: "Breaking Bad",
    posterUrl: "https://image.tmdb.org/t/p/w342/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg",
    year: 2008,
  },
  "tmdb:tv:60059": {
    title: "Better Call Saul",
    posterUrl: "https://image.tmdb.org/t/p/w342/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    year: 2015,
  },
  "tmdb:tv:1399": {
    title: "Juego de tronos",
    posterUrl: "https://image.tmdb.org/t/p/w342/3hDtRuwTfQQYRst3kjhvp4Cogjw.jpg",
    year: 2011,
  },
  "tmdb:tv:94997": {
    title: "La casa del dragón",
    posterUrl: "https://image.tmdb.org/t/p/w342/8MaxftF69sEAAD5673vTjIl8yT3.jpg",
    year: 2022,
  },
  "tmdb:tv:1402": {
    title: "The Walking Dead",
    posterUrl: "https://image.tmdb.org/t/p/w342/hUblG1KZCTRpHc3wqqoU0DW98Q3.jpg",
    year: 2010,
  },
  "tmdb:tv:62286": {
    title: "Fear the Walking Dead",
    posterUrl: "https://image.tmdb.org/t/p/w342/rdaB95H0qnBd2Y3j8FOjUkxBuBk.jpg",
    year: 2015,
  },
  "tmdb:tv:94305": {
    title: "The Walking Dead: World Beyond",
    posterUrl: "https://image.tmdb.org/t/p/w342/6HanIV2hTLE2w7A5bI1KJb3bTL7.jpg",
    year: 2020,
  },
  "tmdb:tv:136248": {
    title: "Tales of the Walking Dead",
    posterUrl: "https://image.tmdb.org/t/p/w342/zRMUHvTgQ79zteQafNI46Nd9XFm.jpg",
    year: 2022,
  },
  "tmdb:tv:194583": {
    title: "The Walking Dead: Dead City",
    posterUrl: "https://image.tmdb.org/t/p/w342/wq3vuQzQgbS83zX3malAFWMsSwX.jpg",
    year: 2023,
  },
  "tmdb:tv:211684": {
    title: "The Walking Dead: Daryl Dixon",
    posterUrl: "https://image.tmdb.org/t/p/w342/1e6y2MiGL7KCTJfpqa3cNHLDpF3.jpg",
    year: 2023,
  },
  "tmdb:tv:206586": {
    title: "The Walking Dead: The Ones Who Live",
    posterUrl: "https://image.tmdb.org/t/p/w342/ywbacot78IuNhGW4uVZPxxxVTkm.jpg",
    year: 2024,
  },
  "tmdb:tv:73586": {
    title: "Yellowstone",
    posterUrl: "https://image.tmdb.org/t/p/w342/8mPGPuSx8NbSDmjABbEqlja0I96.jpg",
    year: 2018,
  },
  "tmdb:tv:118357": {
    title: "1883",
    posterUrl: "https://image.tmdb.org/t/p/w342/waLbm384SQDwLTCn6ttPqQS5kfV.jpg",
    year: 2021,
  },
  "tmdb:tv:157744": {
    title: "1923",
    posterUrl: "https://image.tmdb.org/t/p/w342/aE7pMhO58iCn9CdU1VYcyTfKr1o.jpg",
    year: 2022,
  },
  "tmdb:tv:44217": {
    title: "Vikingos",
    posterUrl: "https://image.tmdb.org/t/p/w342/x0BOmMjIslyH9ZP5h2eMOdaZ8QX.jpg",
    year: 2013,
  },
  "tmdb:tv:116135": {
    title: "Vikingos: Valhalla",
    posterUrl: "https://image.tmdb.org/t/p/w342/hZfPArlmeLS18oecv5yErmmf9lo.jpg",
    year: 2022,
  },
  "tmdb:tv:1405": {
    title: "Dexter",
    posterUrl: "https://image.tmdb.org/t/p/w342/q8dWfc4JwQuv3HayIZeO84jAXED.jpg",
    year: 2006,
  },
  "tmdb:tv:131927": {
    title: "Dexter: New Blood",
    posterUrl: "https://image.tmdb.org/t/p/w342/9EBKgrFIsCFSV1RZKWhYUdbtGiv.jpg",
    year: 2021,
  },
  "tmdb:tv:219937": {
    title: "Dexter: Pecado Original",
    posterUrl: "https://image.tmdb.org/t/p/w342/9XLULEZTkeLwRytTUQtgmx2HH4o.jpg",
    year: 2024,
  },
  "tmdb:tv:259909": {
    title: "Dexter: Resurrección",
    posterUrl: "https://image.tmdb.org/t/p/w342/lZyvtYfG6RMJm3B6sjfJvcTVtFw.jpg",
    year: 2025,
  },
  "tmdb:tv:67198": {
    title: "Star Trek: Discovery",
    posterUrl: "https://image.tmdb.org/t/p/w342/xwpOHgym48Ftz7fbJq5te5xoiwu.jpg",
    year: 2017,
  },
  "tmdb:tv:85949": {
    title: "Star Trek: Picard",
    posterUrl: "https://image.tmdb.org/t/p/w342/nIlAKIrLKxOeoEnc0Urb65yNCp.jpg",
    year: 2020,
  },
  "tmdb:tv:85948": {
    title: "Star Trek: Lower Decks",
    posterUrl: "https://image.tmdb.org/t/p/w342/i7Em3r7KCyNfkOwMkyqN8UMvK8S.jpg",
    year: 2020,
  },
  "tmdb:tv:106393": {
    title: "Star Trek: Prodigy",
    posterUrl: "https://image.tmdb.org/t/p/w342/Aqub3PSzLm2F398vitkbkxjopjO.jpg",
    year: 2021,
  },
  "tmdb:tv:103516": {
    title: "Star Trek: Strange New Worlds",
    posterUrl: "https://image.tmdb.org/t/p/w342/w6KapI2JvrCkOPmQhkwYPJNjqeo.jpg",
    year: 2022,
  },
  "tmdb:tv:246": {
    title: "Avatar: La leyenda de Aang",
    posterUrl: "https://image.tmdb.org/t/p/w342/ucNtkZfpZ6KgxqPo039nN4LAyFR.jpg",
    year: 2005,
  },
  "tmdb:tv:33880": {
    title: "La leyenda de Korra",
    posterUrl: "https://image.tmdb.org/t/p/w342/eMo4uWsN3qceNhBPcuw5T2lFsc5.jpg",
    year: 2012,
  },
  "tmdb:tv:71912": {
    title: "The Witcher",
    posterUrl: "https://image.tmdb.org/t/p/w342/gvn0m0LCIslrURjSo7UG5Rx6mV2.jpg",
    year: 2019,
  },
  "tmdb:tv:106541": {
    title: "The Witcher: El origen de la sangre",
    posterUrl: "https://image.tmdb.org/t/p/w342/3BRkE6xK6uO6ov7EvYZDgkg5Ub3.jpg",
    year: 2022,
  },
  "tmdb:tv:82856": {
    title: "The Mandalorian",
    posterUrl: "https://image.tmdb.org/t/p/w342/iLg3DzrwCDsHNovNaWx5JnQAsiV.jpg",
    year: 2019,
  },
  "tmdb:tv:115036": {
    title: "El libro de Boba Fett",
    posterUrl: "https://image.tmdb.org/t/p/w342/4bffB2YV4UxNfEifp4HxdhfJulK.jpg",
    year: 2021,
  },
  "tmdb:tv:92830": {
    title: "Obi-Wan Kenobi",
    posterUrl: "https://image.tmdb.org/t/p/w342/mVHpVzGwhB9NBpyS5j6qJsME7lo.jpg",
    year: 2022,
  },
  "tmdb:tv:83867": {
    title: "Andor",
    posterUrl: "https://image.tmdb.org/t/p/w342/e3cWQzBxHK803AbZGjp1feQFgyS.jpg",
    year: 2022,
  },
  "tmdb:tv:114461": {
    title: "Ahsoka",
    posterUrl: "https://image.tmdb.org/t/p/w342/co7oZ7eupt4t5o1MkTvqBpsaR0M.jpg",
    year: 2023,
  },
  "tmdb:tv:4629": {
    title: "Stargate SG-1",
    posterUrl: "https://image.tmdb.org/t/p/w342/dQjmI7XxI47v8IM2MUysHG0LuU2.jpg",
    year: 1997,
  },
  "tmdb:tv:2290": {
    title: "Stargate Atlantis",
    posterUrl: "https://image.tmdb.org/t/p/w342/l0JYr2iqwId6VOmCV8dHzlIM6Wd.jpg",
    year: 2004,
  },
  "tmdb:tv:5148": {
    title: "Stargate Universe",
    posterUrl: "https://image.tmdb.org/t/p/w342/dHOaOZGUhnoRXeK9mhYeSRPh59H.jpg",
    year: 2009,
  },
  "tmdb:tv:1412": {
    title: "Arrow",
    posterUrl: "https://image.tmdb.org/t/p/w342/u8ZHFj1jC384JEkTt3vNg1DfWEb.jpg",
    year: 2012,
  },
  "tmdb:tv:60735": {
    title: "The Flash",
    posterUrl: "https://image.tmdb.org/t/p/w342/7ci4qqkBJorLxSBwTj28vwh0bU.jpg",
    year: 2014,
  },
  "tmdb:tv:62688": {
    title: "Supergirl",
    posterUrl: "https://image.tmdb.org/t/p/w342/VsvR3ykugenhyRzz1Uf91V9U0c.jpg",
    year: 2015,
  },
  "tmdb:tv:62643": {
    title: "DC's Legends of Tomorrow",
    posterUrl: "https://image.tmdb.org/t/p/w342/RChURu0ZBfHQ5f5t3aDJiq0M4s.jpg",
    year: 2016,
  },
  "tmdb:tv:89247": {
    title: "Batwoman",
    posterUrl: "https://image.tmdb.org/t/p/w342/uMOZ7VZwGbHcoiMksZjvyO5AFRT.jpg",
    year: 2019,
  },
  "tmdb:tv:76479": {
    title: "The Boys",
    posterUrl: "https://image.tmdb.org/t/p/w342/5kgY14oisiHcJ4zq0Xgq1e97PHm.jpg",
    year: 2019,
  },
  "tmdb:tv:205715": {
    title: "Generación V",
    posterUrl: "https://image.tmdb.org/t/p/w342/fLJzwWk28vRrNQIvIXUSU5YBdT5.jpg",
    year: 2023,
  },
  "tmdb:tv:61889": {
    title: "Marvel - Daredevil",
    posterUrl: "https://image.tmdb.org/t/p/w342/zdjmPOMNlDpmqXLgNaGBT7jAiFj.jpg",
    year: 2015,
  },
  "tmdb:tv:38472": {
    title: "Marvel - Jessica Jones",
    posterUrl: "https://image.tmdb.org/t/p/w342/b3EVT7sSX8Y8L3OekYWyKLRS1Jt.jpg",
    year: 2015,
  },
  "tmdb:tv:62126": {
    title: "Marvel - Luke Cage",
    posterUrl: "https://image.tmdb.org/t/p/w342/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
    year: 2016,
  },
  "tmdb:tv:62127": {
    title: "Marvel - Iron Fist",
    posterUrl: "https://image.tmdb.org/t/p/w342/ywrvjIgK5K9Ff8RddgdFI3kfDqT.jpg",
    year: 2017,
  },
  "tmdb:tv:62285": {
    title: "Marvel - The Defenders",
    posterUrl: "https://image.tmdb.org/t/p/w342/49XzINhH4LFsgz7cx6TOPcHUJUL.jpg",
    year: 2017,
  },
  "tmdb:tv:67178": {
    title: "Marvel - The Punisher",
    posterUrl: "https://image.tmdb.org/t/p/w342/8OdIbo68mFE4w6jXA20aL8ocPsE.jpg",
    year: 2017,
  },
};
